apiVersion: v2
name: promtail
description: Helm chart for Grafana Promtail
type: application
appVersion: 0.2.0
version: 0.2.0
dependencies:
  - name: promtail
    alias: promtail
    version: 6.16.4
    repository: https://grafana.github.io/helm-charts
