{
 "title": "User Audit",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Azure IDIR Logins/10min Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time(  {environment=\"prod\"}  |= `type=LOGIN` |=`identity_provider=azureidir` |=`realmId=standard`  [10m])) by (clientId)"
    }
   ]
  },
  {
   "title": "Azueidir logins by client ID",
   "type": "timeseries",
   "description": "The number of azure Idir logins per 10 minutes ",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time(  {environment=\"prod\"}  |= `type=LOGIN` |=`identity_provider=azureidir` |=`realmId=standard` |= `clientId=` | regexp \".*clientId=(?P<clientId>\\\\S+),\" [10m])) by (clientId)"
    }
   ]
  },
  {
   "title": "Azure IDIR Logins by userID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(count_over_time(  {environment=\"prod\"}  |= `type=LOGIN` |=`identity_provider=azureidir` |=`realmId=standard` |= `userId=` | regexp \".*userId=(?P<userId>\\\\S+),\" [10m])) by (userId)"
    }
   ]
  },
  {
   "title": "User Audit",
   "type": "timeseries",
   "description": "Get all events based on user email",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  }
 ]
}