# see https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
promtail:
  nameOverride: null
  fullnameOverride: null

  daemonset:
    enabled: false

  deployment:
    enabled: true
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage:

  image:
    registry: docker.io
    repository: grafana/promtail
    tag: null
    pullPolicy: IfNotPresent

  imagePullSecrets: []

  resources: {}
  #  limits:
  #    cpu: 200m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi

  podSecurityContext:
  containerSecurityContext:

  rbac:
    create: false
    pspEnabled: false

  serviceAccount:
    create: false

  defaultVolumes:
    - name: positions
      persistentVolumeClaim:
        claimName: sso-promtail-positions

  defaultVolumeMounts:
    - name: positions
      mountPath: /run/promtail

  podSecurityPolicy:

persistentVolume:
  size: 100Mi
  storageClass: netapp-file-standard
  annotations: {}
  accessModes:
    - ReadWriteMany
