apiVersion: v2
name: grafana
description: Helm chart for Grafana
type: application
appVersion: 0.1.1
version: 0.1.1
dependencies:
  - name: grafana
    alias: grafana
    version: 12.4.1
    repository: https://grafana-community.github.io/helm-charts
