grafana:
  replicas: 1
  persistence:
    size: 1Gi

  grafana.ini:
    server:
      domain: sso-grafana.apps.gold.devops.gov.bc.ca
      root_url: https://sso-grafana.apps.gold.devops.gov.bc.ca
    auth:
      disable_login_form: true
    auth.generic_oauth:
      name: SSO Pathfinder
      auth_url: https://loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/auth
      token_url: https://loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: SSO Logs
          type: postgres
          access: proxy
          orgId: 1
          url: kc-cron-patroni-readonly:5432
          user: <please-replace-me>
          database: <please-replace-me>
          basicAuth: false
          secureJsonData:
            password: <please-replace-me>
          jsonData:
            sslmode: disable
            maxOpenConns:
            maxIdleConns: 2
            connMaxLifetime: 14400
            postgresVersion: 1400
            timescaledb: false
        - name: SSO Keycloak Dev
          type: postgres
          access: proxy
          orgId: 1
          url: sso-patroni-readonly.eb75ad-dev.svc.cluster.local:5432
          user: <please-replace-me>
          database: <please-replace-me>
          basicAuth: false
          secureJsonData:
            password: <please-replace-me>
          jsonData:
            sslmode: disable
            maxOpenConns:
            maxIdleConns: 2
            connMaxLifetime: 14400
            postgresVersion: 1400
            timescaledb: false
        - name: SSO Keycloak Test
          type: postgres
          access: proxy
          orgId: 1
          url: sso-patroni-readonly.eb75ad-test.svc.cluster.local:5432
          user: <please-replace-me>
          database: <please-replace-me>
          basicAuth: false
          secureJsonData:
            password: <please-replace-me>
          jsonData:
            sslmode: disable
            maxOpenConns:
            maxIdleConns: 2
            connMaxLifetime: 14400
            postgresVersion: 1400
            timescaledb: false
        - name: SSO Keycloak Prod
          type: postgres
          access: proxy
          orgId: 1
          url: sso-patroni-readonly.eb75ad-prod.svc.cluster.local:5432
          user: <please-replace-me>
          database: <please-replace-me>
          basicAuth: false
          secureJsonData:
            password: <please-replace-me>
          jsonData:
            sslmode: disable
            maxOpenConns:
            maxIdleConns: 2
            connMaxLifetime: 14400
            postgresVersion: 1400
            timescaledb: false

route:
  enabled: true
  host: sso-grafana.apps.gold.devops.gov.bc.ca
