grafana:
  replicas: 2
  persistence:
    size: 5Gi

  grafana.ini:
    server:
      domain: sso-grafana.apps.gold.devops.gov.bc.ca
      root_url: https://sso-grafana.apps.gold.devops.gov.bc.ca
    auth.generic_oauth:
      auth_url: https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/auth
      token_url: https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token

route:
  enabled: true
  host: sso-grafana.apps.gold.devops.gov.bc.ca
