# see https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
grafana:
  nameOverride: sso-grafana
  fullnameOverride: sso-grafana
  imagePullSecrets: []

  rbac:
    create: false
    pspEnabled: false
    pspUseAppArmor: false

  serviceAccount:
    create: false

  replicas: 1

  podDisruptionBudget: {}
  #  minAvailable: 1
  #  maxUnavailable: 1

  image:
    repository: grafana/grafana
    tag: "9.3.2"
    pullPolicy: IfNotPresent
    pullSecrets: []

  testFramework:
    enabled: false

  securityContext:
  containerSecurityContext:
  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi

  persistence:
    type: pvc
    enabled: true
    storageClassName: netapp-file-standard
    accessModes:
      - ReadWriteMany
    size: 5Gi

  initChownData:
    enabled: false

  sidecar:
    securityContext:

  adminUser: admin
  # adminPassword: strongpassword

route:
  enabled: true
  host:
  serviceName: sso-grafana
