grafana:
  replicas: 1
  persistence:
    size: 1Gi

  grafana.ini:
    server:
      domain: sso-grafana-sandbox.apps.gold.devops.gov.bc.ca
      root_url: https://sso-grafana-sandbox.apps.gold.devops.gov.bc.ca
    auth.generic_oauth:
      name: SSO Pathfinder Sandbox
      auth_url: https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/auth
      token_url: https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token
      client_id: $__file{/etc/secrets/auth_generic_oauth/SSO_CLIENT_ID}
      client_secret: $__file{/etc/secrets/auth_generic_oauth/SSO_CLIENT_SECRET}

  extraSecretMounts:
    - name: sso-grafana-env-secret-mount
      secretName: sso-grafana-ghaction-env
      defaultMode: 0440
      mountPath: /etc/secrets/auth_generic_oauth
      readOnly: true

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: SSO Keycloak Dev
          type: postgres
          access: proxy
          orgId: 1
          url: sso-patroni-readonly.e4ca1d-dev.svc.cluster.local:5432
          user:  $__file{/etc/secrets/auth_generic_oauth/DS_KEYCLOAK_DEV_USERNAME}
          basicAuth: false
          secureJsonData:
            password: $__file{/etc/secrets/auth_generic_oauth/DS_KEYCLOAK_DEV_PASSWORD}
          jsonData:
            database: $__file{/etc/secrets/auth_generic_oauth/DS_KEYCLOAK_DEV_DATABASE}
            sslmode: disable
            maxOpenConns:
            maxIdleConns: 2
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
        - name: SSO Keycloak Test
          type: postgres
          access: proxy
          orgId: 1
          url: sso-patroni-readonly.e4ca1d-test.svc.cluster.local:5432
          user:  $__file{/etc/secrets/auth_generic_oauth/DS_KEYCLOAK_TEST_USERNAME}
          basicAuth: false
          secureJsonData:
            password: $__file{/etc/secrets/auth_generic_oauth/DS_KEYCLOAK_TEST_PASSWORD}
          jsonData:
            database: $__file{/etc/secrets/auth_generic_oauth/DS_KEYCLOAK_TEST_DATABASE}
            sslmode: disable
            maxOpenConns:
            maxIdleConns: 2
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
        - name: SSO Keycloak Prod
          type: postgres
          access: proxy
          orgId: 1
          url: sso-patroni-readonly.e4ca1d-prod.svc.cluster.local:5432
          user:  $__file{/etc/secrets/auth_generic_oauth/DS_KEYCLOAK_PROD_USERNAME}
          basicAuth: false
          secureJsonData:
            password: $__file{/etc/secrets/auth_generic_oauth/DS_KEYCLOAK_PROD_PASSWORD}
          jsonData:
            database: $__file{/etc/secrets/auth_generic_oauth/DS_KEYCLOAK_PROD_DATABASE}
            sslmode: disable
            maxOpenConns:
            maxIdleConns: 2
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
        - name: SSO Loki
          type: loki
          access: proxy
          orgId: 1
          url: $__file{/etc/secrets/auth_generic_oauth/API_GATEWAY_URL}
          basicAuth: false
          isDefault: true
          jsonData:
            httpHeaderName1: 'Authorization'
          secureJsonData:
            httpHeaderValue1: $__file{/etc/secrets/auth_generic_oauth/LOKI_AUTH_TOKEN} #This needs to be modified to be Bearer LOKI....
        - name: SSO Aggregator
          type: postgres
          access: proxy
          orgId: 1
          url: sso-aggregator-patroni-readonly.e4ca1d-prod.svc.cluster.local:5432
          user: $__file{/etc/secrets/auth_generic_oauth/DS_AGGREGATOR_USERNAME}
          basicAuth: false
          secureJsonData:
            password: $__file{/etc/secrets/auth_generic_oauth/DS_AGGREGATOR_PASSWORD}
          jsonData:
            database: $__file{/etc/secrets/auth_generic_oauth/DS_AGGREGATOR_DATABASE}
            sslmode: disable
            maxOpenConns:
            maxIdleConns: 2
            connMaxLifetime: 14400
            postgresVersion: 1400
            timescaledb: false
        - name: CSS App
          type: postgres
          access: proxy
          orgId: 1
          url: sso-requests-patroni-readonly.b29129-dev.svc.cluster.local:5432
          user: $__file{/etc/secrets/auth_generic_oauth/DS_CSS_USERNAME}
          basicAuth: false
          secureJsonData:
            password: $__file{/etc/secrets/auth_generic_oauth/DS_CSS_PASSWORD}
          jsonData:
            database: $__file{/etc/secrets/auth_generic_oauth/DS_CSS_DATABASE}
            sslmode: disable
            maxOpenConns:
            maxIdleConns: 2
            connMaxLifetime: 14400
            postgresVersion: 1400
            timescaledb: false
        - name: Realm Registry
          type: postgres
          access: proxy
          orgId: 1
          url: realm-registry-patroni.c6af30-dev.svc.cluster.local:5432
          user: $__file{/etc/secrets/auth_generic_oauth/DS_REALM_REGISTRY_USERNAME}
          basicAuth: false
          secureJsonData:
            password: $__file{/etc/secrets/auth_generic_oauth/DS_REALM_REGISTRY_PASSWORD}
          jsonData:
            database: $__file{/etc/secrets/auth_generic_oauth/DS_REALM_REGISTRY_DATABASE}
            sslmode: disable
            maxOpenConns:
            maxIdleConns: 2
            connMaxLifetime: 14400
            postgresVersion: 1400
            timescaledb: false
        - name: SIEM Trino
          type: trino-datasource
          access: proxy
          orgId: 1
          url: $__file{/etc/secrets/auth_generic_oauth/DS_TRINO_URL}
          basicAuth: true
          basicAuthUser: $__file{/etc/secrets/auth_generic_oauth/DS_TRINO_USERNAME}
          isDefault: false
          secureJsonData:
            basicAuthPassword: $__file{/etc/secrets/auth_generic_oauth/DS_TRINO_PASSWORD}
          jsonData:
            withCredentials: false
route:
  enabled: true
  host: sso-grafana-sandbox.apps.gold.devops.gov.bc.ca
