# see https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
grafana:
  nameOverride: sso-grafana
  fullnameOverride: sso-grafana
  imagePullSecrets: []

  rbac:
    create: false
    pspEnabled: false
    pspUseAppArmor: false

  serviceAccount:
    create: false

  replicas: 1

  podDisruptionBudget: {}
  #  minAvailable: 1
  #  maxUnavailable: 1

  image:
    repository: grafana/grafana
    tag: '10.2.2'
    pullPolicy: IfNotPresent
    pullSecrets: []

  testFramework:
    enabled: false

  securityContext:
  containerSecurityContext:
  resources:
    limits:
      cpu: 250m
      memory: 2Gi
    requests:
      cpu: 150m
      memory: 512Mi

  persistence:
    type: pvc
    enabled: true
    storageClassName: netapp-file-standard
    accessModes:
      - ReadWriteMany
    size: 5Gi

  initChownData:
    enabled: false

  sidecar:
    securityContext:

  adminUser: admin
  # adminPassword: strongpassword

  # see https://github.com/kubeflow/community/blob/master/devstats/config/grafana/etc/grafana.ini.example
  grafana.ini:
    server:
      domain: sso-grafana-sandbox.gov.bc.ca
      root_url: https://sso-grafana-sandbox.gov.bc.ca
    auth:
      disable_login_form: true
      oauth_allow_insecure_email_lookup: true
    auth.generic_oauth:
      enabled: true
      name: Keycloak
      icon: signin
      scopes: openid
      empty_scopes: false
      client_id: <please-replace-me>
      client_secret: <please-replace-me>
      auth_url: https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/auth
      token_url: https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token
      api_url:
      allowed_domains:
      allow_sign_up: true
      tls_skip_verify_insecure: true
      use_pkce: true
      login_attribute_path: preferred_username
      role_attribute_path: contains(client_roles[*], 'grafanaadmin') && 'GrafanaAdmin' || contains(client_roles[*], 'admin') && 'Admin' || contains(client_roles[*], 'editor') && 'Editor' || 'Viewer'
    dataproxy:
      timeout: 500
      keep_alive_seconds: 500
      idle_conn_timeout_seconds: 500
      logging: true
  # see https://github.com/kubeflow/community/blob/master/devstats/config/grafana/provisioning/datasources/datasource.yaml

route:
  enabled: true
  host:
  serviceName: sso-grafana
