grafana:
  replicas: 1
  persistence:
    size: 1Gi

  grafana.ini:
    server:
      domain: sso-grafana-sandbox.apps.gold.devops.gov.bc.ca
      root_url: https://sso-grafana-sandbox.apps.gold.devops.gov.bc.ca
    auth.generic_oauth:
      name: SSO Pathfinder Sandbox
      auth_url: https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/auth
      token_url: https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: SSO Logs
          type: postgres
          access: proxy
          orgId: 1
          url: kc-cron-patroni-readonly:5432
          user: <please-replace-me>
          database: <please-replace-me>
          basicAuth: false
          secureJsonData:
            password: <please-replace-me>
          jsonData:
            sslmode: disable
            maxOpenConns:
            maxIdleConns: 2
            connMaxLifetime: 14400
            postgresVersion: 1400
            timescaledb: false
        - name: SSO Keycloak Dev
          type: postgres
          access: proxy
          orgId: 1
          url: sso-patroni-readonly.e4ca1d-dev.svc.cluster.local:5432
          user: <please-replace-me>
          database: <please-replace-me>
          basicAuth: false
          secureJsonData:
            password: <please-replace-me>
          jsonData:
            sslmode: disable
            maxOpenConns:
            maxIdleConns: 2
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
        - name: SSO Keycloak Test
          type: postgres
          access: proxy
          orgId: 1
          url: sso-patroni-readonly.e4ca1d-test.svc.cluster.local:5432
          user: <please-replace-me>
          database: <please-replace-me>
          basicAuth: false
          secureJsonData:
            password: <please-replace-me>
          jsonData:
            sslmode: disable
            maxOpenConns:
            maxIdleConns: 2
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
        - name: SSO Keycloak Prod
          type: postgres
          access: proxy
          orgId: 1
          url: sso-patroni-readonly.e4ca1d-prod.svc.cluster.local:5432
          user: <please-replace-me>
          database: <please-replace-me>
          basicAuth: false
          secureJsonData:
            password: <please-replace-me>
          jsonData:
            sslmode: disable
            maxOpenConns:
            maxIdleConns: 2
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
        - name: SSO Loki
          type: loki
          access: proxy
          orgId: 1
          url: https://qcvs5jdpkd.execute-api.ca-central-1.amazonaws.com
          basicAuth: false
          isDefault: true
          jsonData:
            httpHeaderName1: "Authorization"
          secureJsonData:
            httpHeaderValue1: <please-replace-me>
        - name: SSO Aggregator
          type: postgres
          access: proxy
          orgId: 1
          url: sso-aggregator-patroni-readonly.e4ca1d-prod.svc.cluster.local:5432
          user: <please-replace-me>
          database: <please-replace-me>
          basicAuth: false
          secureJsonData:
            password: <please-replace-me>
          jsonData:
            sslmode: disable
            maxOpenConns:
            maxIdleConns: 2
            connMaxLifetime: 14400
            postgresVersion: 1400
            timescaledb: false

route:
  enabled: true
  host: sso-grafana-sandbox.apps.gold.devops.gov.bc.ca
