grafana:
  replicas: 1
  persistence:
    size: 5Gi

  # see https://github.com/kubeflow/community/blob/master/devstats/config/grafana/etc/grafana.ini.example
  grafana.ini:
    server:
      domain: sso-grafana-sandbox.apps.gold.devops.gov.bc.ca
      root_url: https://sso-grafana-sandbox.apps.gold.devops.gov.bc.ca
    auth.generic_oauth:
      enabled: true
      name: Keycloak
      icon: signin
      scopes: openid
      empty_scopes: false
      client_id: <please-replace-me>
      client_secret: <please-replace-me>
      auth_url: <please-replace-me>
      token_url: <please-replace-me>
      api_url:
      allowed_domains:
      allow_sign_up: true
      tls_skip_verify_insecure: true
      use_pkce: true
      login_attribute_path: preferred_username

route:
  enabled: true
  host: sso-grafana-sandbox.apps.gold.devops.gov.bc.ca
