# see https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
promtail:
  nameOverride: sso-promtail-agregator
  fullnameOverride: sso-promtail-aggregator

  daemonset:
    enabled: false

  deployment:
    enabled: true
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage:

  image:
    registry: docker.io
    repository: grafana/promtail
    tag: ""
    pullPolicy: IfNotPresent

  imagePullSecrets: []

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  podSecurityContext:
  containerSecurityContext:

  rbac:
    create: false
    pspEnabled: false

  serviceAccount:
    create: false

  podSecurityPolicy:

  defaultVolumes:
    - name: positions
      persistentVolumeClaim:
        claimName: sso-promtail-aggregator-positions

  defaultVolumeMounts:
    - name: positions
      mountPath: /run/promtail

  extraVolumes:
    - name: logs-volume
      persistentVolumeClaim:
        claimName: sso-keycloak-logs

  extraVolumeMounts:
    - mountPath: /keycloak/logs
      name: logs-volume

  ssoScrapeConfigs: |
    - job_name: local
      static_configs:
      - targets:
          - localhost
        labels:
          job: keycloak
          environment: {{ .Values.environment }}
          __path__: /keycloak/logs/*.log
      pipeline_stages:
      - match:
          selector: '{job="keycloak"}'
          stages:
          - json:
              expressions:
                timestamp: '"@timestamp"'
                level: level
          - labels:
              level:
          - timestamp:
              format: RFC3339Nano
              source: timestamp
      - match:
          selector: '{job="keycloak"}'
          stages:
          - regex:
              expression: "type=(?P<type>\\S+),.*realmId=(?P<realm_id>\\S+),.*clientId=(?P<client_id>\\S+),"
          - labels:
              event_type: type
              realm_id:
              client_id:

persistentVolume:
  size: 100Mi
  storageClass: netapp-file-standard
  annotations: {}
  accessModes:
    - ReadWriteMany
