"""create sessions table

Revision ID: 5bfc2a71a71f
Revises: 3999a4f6f9c0
Create Date: 2024-05-15 17:05:50.453140

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '5bfc2a71a71f'
down_revision = '3999a4f6f9c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_sessions',
    sa.Column('environment', sa.String(length=255), nullable=False),
    sa.Column('realm_id', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('active_sessions', sa.Integer(), nullable=False),
    sa.Column('offline_sessions', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.func.current_timestamp()),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_sessions')
    # ### end Alembic commands ###
