"""create an IDP table

Revision ID: a21a49fdc853
Revises: 7c002818cb32
Create Date: 2025-07-22 11:47:52.549986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21a49fdc853'
down_revision = '7c002818cb32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_events_with_idp',
    sa.Column('environment', sa.String(length=255), nullable=False),
    sa.Column('realm_id', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('idp',sa.String(length=255), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('environment', 'realm_id', 'client_id', 'event_type', 'date', 'idp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_login_events_with_idp')
    # ### end Alembic commands ###
