replicaCount: 1

image:
  repository: ghcr.io/bcgov/sso-aggregator
  tag: dev
  pullPolicy: IfNotPresent

patroni:
  replicaCount: 2
  persistentVolume:
    size: 1Gi

compactor:
  enabled: true
  retentionPeriod: '3 months'
  secret: sso-aggregator

autoscaling:
  enabled: true
