replicaCount: 1

image:
  repository: ghcr.io/bcgov/sso-aggregator
  tag: main
  pullPolicy: IfNotPresent

patroni:
  replicaCount: 2
  persistentVolume:
    size: 3Gi

compactor:
  enabled: true
  retentionPeriod: '6 months'
  secret: sso-aggregator


autoscaling:
  enabled: true
  maxReplicas: 5

resources:
  limits:
    cpu: 300m
    memory: 1Gi
  requests:
    cpu: 150m
    memory: 512Mi
