{{- if .Values.routes.minio.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.routes.minio.serviceName }}
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: 'true'
    haproxy.router.openshift.io/timeout: '30'
spec:
  {{- if .Values.routes.minio.host }}
  host: {{ .Values.routes.minio.host }}
  {{- end }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.routes.minio.serviceName }}
{{- end }}
