apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: sso-dashboard-deployer-role-template
objects:
- kind: Role
  apiVersion: authorization.openshift.io/v1
  metadata:
    name: sso-dashboard-deployer-${NAMESPACE}
    namespace: ${NAMESPACE}
    labels:
      created-by: local
      role: deployer
    annotations:
      openshift.io/description: deployer
      openshift.io/reconcile-protect: 'false'
  rules:
  - verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
    attributeRestrictions:
    apiGroups:
    - ''
    resources:
    - configmaps
    - endpoints
    - persistentvolumeclaims
    - pods
    - pods/exec
    - replicationcontrollers
    - secrets
    - services
  - verbs:
    - get
    - list
    - watch
    attributeRestrictions:
    apiGroups:
    - ''
    resources:
    - pods/log
    - pods/status
  - verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    attributeRestrictions:
    apiGroups:
    - ''
    resources:
    - serviceaccounts
  - verbs:
    - list
    attributeRestrictions:
    apiGroups:
    - ''
    resources:
    - events
  - verbs:
    - get
    - list
    - update
    - watch
    attributeRestrictions:
    apiGroups:
    - image.openshift.io
    resources:
    - imagestreamimages
    - imagestreammappings
    - imagestreams
    - imagestreamtags
  - verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    attributeRestrictions:
    apiGroups:
    - apps
    resources:
    - statefulsets
  - verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
    attributeRestrictions:
    apiGroups:
    - batch
    resources:
    - cronjobs
    - jobs
  - verbs:
    - create
    - delete
    - get
    - patch
    - update
    attributeRestrictions:
    apiGroups:
    - policy
    resources:
    - poddisruptionbudgets
  - verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    attributeRestrictions:
    apiGroups:
    - rbac.authorization.k8s.io
    - authorization.openshift.io
    resources:
    - rolebindings
    - roles
  - verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    attributeRestrictions:
    apiGroups:
    - apps
    - extensions
    resources:
    - deployments
    - replicasets
  - verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    attributeRestrictions:
    apiGroups:
    - networking.k8s.io
    resources:
    - networkpolicies
  - verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    attributeRestrictions:
    apiGroups:
    - autoscaling
    resources:
    - horizontalpodautoscalers
  - verbs:
    - delete
    attributeRestrictions:
    apiGroups:
    - image.openshift.io
    resources:
    - imagestreamtags
  - verbs:
    - get
    attributeRestrictions:
    apiGroups:
    - project.openshift.io
    resources:
    - projects
  - verbs:
    - create
    - get
    - patch
    - update
    attributeRestrictions:
    apiGroups:
    - apps.openshift.io
    resources:
    - deploymentconfigs
  - verbs:
    - create
    - delete
    - get
    - patch
    - update
    attributeRestrictions:
    apiGroups:
    - route.openshift.io
    resources:
    - routes
  - verbs:
    - create
    attributeRestrictions:
    apiGroups:
    - route.openshift.io
    resources:
    - routes/custom-host
  - verbs:
    - create
    attributeRestrictions:
    apiGroups:
    - template.openshift.io
    resources:
    - processedtemplates
  - verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    attributeRestrictions:
    apiGroups:
    - ops.gov.bc.ca
    resources:
    - sysdig-teams
  - verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    attributeRestrictions:
    apiGroups:
    - porter.devops.gov.bc.ca
    resources:
    - transportserverclaims
parameters:
- name: NAMESPACE
  required: true
  description: the namespace the role is built in
