{
 "title": "Login Metrics Exec View",
 "time": { "from": "2023-09-20T00:00:00.000Z", "to": "2023-10-17T00:00:00.000Z" },
 "panels": [
  { "title": "Total Logins Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total logins over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select sum(login) + sum(client_login) as total_logins, date from sso_stats where date > NOW() - INTERVAL '60 days' group by date\norder by date desc;"
    }
   ]
  },
  {
   "title": "Logins Monthly From SSO Stats PROD",
   "type": "timeseries",
   "description": "Please use the time range of the last year",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n   DATE_TRUNC('month',\"public\".\"sso_stats\".\"date\") AS month,\n  SUM(\"public\".\"sso_stats\".\"login\") AS \"sum\"\nFROM\n  \"public\".\"sso_stats\"\nWHERE\n  \n    (\"public\".\"sso_stats\".\"date\" < date_trunc('month', NOW() ) )\n  AND (\"public\".\"sso_stats\".\"namespace\" = 'eb75ad-prod' OR \"public\".\"sso_stats\".\"namespace\" IS NULL  OR (\"public\".\"sso_stats\".\"namespace\" = ''))\nGROUP BY\nmonth \nORDER BY\n  month"
    }
   ]
  },
  {
   "title": "Logins Monthly From SSO Stats PROD By IDP",
   "type": "barchart",
   "description": "Please use the time range of the last year",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n   DATE_TRUNC('month',\"public\".\"sso_stats\".\"date\") AS month,\n   \"public\".\"sso_stats\".\"realm_id\" AS \"realm\",\n  SUM(\"public\".\"sso_stats\".\"login\") AS \"sum\"\nFROM\n  \"public\".\"sso_stats\"\nWHERE\n  \n    (\"public\".\"sso_stats\".\"date\" < date_trunc('month', NOW() ) )\n  AND (\"public\".\"sso_stats\".\"namespace\" = 'eb75ad-prod' OR \"public\".\"sso_stats\".\"namespace\" IS NULL  OR (\"public\".\"sso_stats\".\"namespace\" = ''))\n  AND (\"public\".\"sso_stats\".\"realm_id\" in ('idir', 'bceidbusiness', 'azureidir', 'bceidbasic', 'bceidboth') )\nGROUP BY\nmonth, realm \nORDER BY\n  month"
    }
   ]
  },
  {
   "title": "Total Number of Logins Non Production since Aug 31 2023",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"public\".\"sso_stats\".\"namespace\" AS \"namespace\",\n  SUM(\"public\".\"sso_stats\".\"login\") AS \"sum\"\nFROM\n  \"public\".\"sso_stats\"\nWHERE\n  (\"public\".\"sso_stats\".\"login\" IS NOT NULL)\n \n   AND (\n    (\"public\".\"sso_stats\".\"namespace\" = 'eb75ad-dev')\n   \n    OR (\"public\".\"sso_stats\".\"namespace\" = 'eb75ad-test')\n  )\nGROUP BY\n  \"public\".\"sso_stats\".\"namespace\"\nORDER BY\n  \"public\".\"sso_stats\".\"namespace\" ASC"
    }
   ]
  },
  {
   "title": "Total Number of Logins Production since Jan 1, 2024",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\"public\".\"sso_stats\".\"login\") AS \"sum\"\nFROM\n  \"public\".\"sso_stats\"\nWHERE\n  (\"public\".\"sso_stats\".\"login\" IS NOT NULL)\n \n   AND (\"public\".\"sso_stats\".\"namespace\" = 'eb75ad-prod' OR \"public\".\"sso_stats\".\"namespace\" IS NULL OR (\"public\".\"sso_stats\".\"namespace\" = ''))\n       AND \"public\".\"sso_stats\".\"date\" >= timestamp with time zone '2024-01-01 00:00:00.000Z'"
    }
   ]
  },
  {
   "title": "Total Number of Logins Production since Sept 1 2023",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\"public\".\"sso_stats\".\"login\") AS \"sum\"\nFROM\n  \"public\".\"sso_stats\"\nWHERE\n  (\"public\".\"sso_stats\".\"login\" IS NOT NULL)\n \n   AND (\"public\".\"sso_stats\".\"namespace\" = 'eb75ad-prod' OR \"public\".\"sso_stats\".\"namespace\" IS NULL OR (\"public\".\"sso_stats\".\"namespace\" = ''))\n       AND \"public\".\"sso_stats\".\"date\" >= timestamp with time zone '2023-09-01 00:00:00.000Z'"
    }
   ]
  },
  {
   "title": "Total Number of Logins Production since May 2022",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\"public\".\"sso_stats\".\"login\") AS \"sum\"\nFROM\n  \"public\".\"sso_stats\"\nWHERE\n  (\"public\".\"sso_stats\".\"login\" IS NOT NULL)\n \n   AND (\"public\".\"sso_stats\".\"namespace\" = 'eb75ad-prod' OR \"public\".\"sso_stats\".\"namespace\" IS NULL OR (\"public\".\"sso_stats\".\"namespace\" = ''))"
    }
   ]
  },
  { "title": "Total Logins last 30 days", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Logins Last 30 Days From SSO Stats DEV",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"public\".\"sso_stats\".\"date\" AS \"date\",\n  SUM(\"public\".\"sso_stats\".\"login\") AS \"sum\"\nFROM\n  \"public\".\"sso_stats\"\nWHERE\n  (\n    \"public\".\"sso_stats\".\"date\" >= CAST((NOW() + INTERVAL '-60 day') AS date)\n  )\n \n   AND (\"public\".\"sso_stats\".\"date\" < CAST(NOW() AS date))\n  AND (\"public\".\"sso_stats\".\"namespace\" = 'eb75ad-dev' )\nGROUP BY\n  \"public\".\"sso_stats\".\"date\"\nORDER BY\n  \"public\".\"sso_stats\".\"date\" ASC"
    }
   ]
  },
  {
   "title": "Logins Last 30 Days From SSO Stats TEST",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"public\".\"sso_stats\".\"date\" AS \"date\",\n  SUM(\"public\".\"sso_stats\".\"login\") AS \"sum\"\nFROM\n  \"public\".\"sso_stats\"\nWHERE\n  (\n    \"public\".\"sso_stats\".\"date\" >= CAST((NOW() + INTERVAL '-60 day') AS date)\n  )\n \n   AND (\"public\".\"sso_stats\".\"date\" < CAST(NOW() AS date))\n  AND (\"public\".\"sso_stats\".\"namespace\" = 'eb75ad-test' )\nGROUP BY\n  \"public\".\"sso_stats\".\"date\"\nORDER BY\n  \"public\".\"sso_stats\".\"date\" ASC"
    }
   ]
  },
  {
   "title": "Logins Last 30 Days From SSO Stats PROD",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"public\".\"sso_stats\".\"date\" AS \"date\",\n  SUM(\"public\".\"sso_stats\".\"login\") AS \"sum\"\nFROM\n  \"public\".\"sso_stats\"\nWHERE\n  (\n    \"public\".\"sso_stats\".\"date\" >= CAST((NOW() + INTERVAL '-60 day') AS date)\n  )\n \n   AND (\"public\".\"sso_stats\".\"date\" < CAST(NOW() AS date))\n  AND (\"public\".\"sso_stats\".\"namespace\" = 'eb75ad-prod' OR \"public\".\"sso_stats\".\"namespace\" IS NULL  OR (\"public\".\"sso_stats\".\"namespace\" = ''))\nGROUP BY\n  \"public\".\"sso_stats\".\"date\"\nORDER BY\n  \"public\".\"sso_stats\".\"date\" ASC"
    }
   ]
  }
 ]
}