{
 "title": "Service Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total clients in Standard and Custom Service",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT now() as \"data as of\""
    }
   ]
  },
  {
   "title": "Custom Realm Total  PROD",
   "type": "stat",
   "description": "does not include standard and idp parent realms",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\r\nselect count(*) \r\nfrom realm where realm.name not in ('idir','azureidir','bceidbusiness','bceidboth','github','master','bceidbasic','standard')"
    }
   ]
  },
  {
   "title": "Standard Service Average Number (All env)",
   "type": "stat",
   "description": "The average number of clients across the dev, test, and production environments.",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS \"Dev Count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  (\"public\".\"client\".\"realm_id\" = 'standard')\r\n \r\n   AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account')\r\n   \r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'broker')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    \"public\".\"client\".\"description\" = 'CSS App Created'\r\n  )"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS \"Test Count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  (\"public\".\"client\".\"realm_id\" = 'standard')\r\n \r\n   AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account')\r\n   \r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'broker')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    \"public\".\"client\".\"description\" = 'CSS App Created'\r\n  )"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS \"Prod Count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  (\"public\".\"client\".\"realm_id\" = 'standard')\r\n \r\n   AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account')\r\n   \r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'broker')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    \"public\".\"client\".\"description\" = 'CSS App Created'\r\n  )"
    }
   ]
  },
  {
   "title": "Number of Clients DEV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS \"Dev Count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  (\"public\".\"client\".\"realm_id\" = 'standard')\r\n \r\n   AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account')\r\n   \r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'broker')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    \"public\".\"client\".\"description\" = 'CSS App Created'\r\n  )"
    }
   ]
  },
  {
   "title": "Number of Clients TEST",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS \"Dev Count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  (\"public\".\"client\".\"realm_id\" = 'standard')\r\n \r\n   AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account')\r\n   \r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'broker')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    \"public\".\"client\".\"description\" = 'CSS App Created'\r\n  )"
    }
   ]
  },
  {
   "title": "Number of Clients PROD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS \"Dev Count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  (\"public\".\"client\".\"realm_id\" = 'standard')\r\n \r\n   AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account')\r\n   \r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'broker')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    \"public\".\"client\".\"description\" = 'CSS App Created'\r\n  )"
    }
   ]
  }
 ]
}