version: '3.9'
services:
  aggregator:
    restart: always
    build:
      context: ..
      dockerfile: Dockerfile
    stdin_open: true
    ports:
    - 8080:8080
    environment:
    - DB_HOSTNAME=postgres
    - DB_DATABASE=aggregation
    - DB_USERNAME=postgres
    - DB_PASSWORD=postgres
    depends_on:
    - postgres

  postgres:
    image: postgres:14.5
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
    - POSTGRES_DB=aggregation
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    ports:
    - 5432:5432

  grafana:
    environment:
    - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
    - sh
    - -euc
    - |
      mkdir -p /etc/grafana/provisioning/datasources
      cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        access: proxy
        orgId: 1
        url: http://loki:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: false

      - name: SSO Aggregator
        type: postgres
        access: proxy
        orgId: 1
        url: postgres:5432
        user: postgres
        database: aggregation
        basicAuth: false
        jsonData:
          sslmode: disable
        secureJsonData:
          password: postgres

      EOF
      /run.sh
    image: grafana/grafana:11.0.0
    ports:
    - 3000:3000

  loki:
    image: grafana/loki:2.9.2
    ports:
    - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml

  alloy:
    image: grafana/alloy:v1.8.0
    volumes:
    - ./config.alloy:/config.alloy
    - keycloak_logs:/alloy-logs
    command:
    - run
    - --server.http.listen-addr=0.0.0.0:12345
    - /config.alloy
    ports:
    - 12345:12345

  # Give keycloak permission to write logs to the docker volume
  keycloak-init:
    image: alpine
    command: >
      sh -c "chown -R 1000:0 /mnt"
    volumes:
    - keycloak_logs:/mnt

  dev-keycloak:
    container_name: dev-keycloak
    image: ghcr.io/bcgov/sso:26.2.4-build.2
    depends_on:
    - postgres
    - keycloak-init
    ports:
    - 9080:9080
    command: start-dev --http-port=9080
    environment:
      DB_POSTGRESQL_SERVICE_HOST: postgres
      DB_POSTGRESQL_SERVICE_PORT: 5432
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      DB_MIN_POOL_SIZE: 1
      DB_MAX_POOL_SIZE: 5
      JGROUPS_CLUSTER_PASSWORD: password
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.impersonation=disabled -Djboss.persistent.log.dir=/var/log/eap -Djgroups.dns.query=disable
      KC_HTTP_RELATIVE_PATH: /auth

      DB_JNDI: java:jboss/datasources/KeycloakDS
      DB_SERVICE_PREFIX_MAPPING: db-postgresql=DB
      TX_DATABASE_PREFIX_MAPPING: db-postgresql=DB
      TZ: America/Vancouver
    volumes:
    - keycloak_logs:/var/log/eap

volumes:
  postgres_data:
    driver: local
  keycloak_logs:
    driver: local
