server:
  http_listen_port: 9081
  log_level: debug

positions:
  filename: /var/log/promtail_positions.yaml

clients:
- url: http://localhost:8080/api/promtail/push
    # Can increase batch interval below to make log batches easier to test
    # batchwait: 10s

scrape_configs:
- job_name: local
  static_configs:
  - targets:
    - localhost
    labels:
      job: keycloak
      environment: dev
      __path__: /keycloak/logs/*.log
  pipeline_stages:
  - match:
      selector: '{job="keycloak"}'
      stages:
      - json:
          expressions:
            timestamp: '"@timestamp"'
            level: level
      - labels:
          level:
      - timestamp:
          format: RFC3339Nano
          source: timestamp
  - match:
      selector: '{job="keycloak"}'
      stages:
      - regex:
          expression: type=(?P<type>\S+),.*realmId=(?P<realm_id>\S+),.*clientId=(?P<client_id>\S+),
      - labels:
          event_type: type
          realm_id:
          client_id:
