loki:
  write:
    replicas: 3
    persistence:
      size: 2Gi

  read:
    replicas: 3
    persistence:
      size: 2Gi

  loki:
    storage:
      s3:
        accessKeyId: <please-replace-me>
        secretAccessKey: <please-replace-me>

root-minio:
  enabled: true
  replicas: 2
  rootUser: <please-replace-me>
  rootPassword: <please-replace-me>
  persistence:
    size: 80Gi
  oidc:
    configUrl: "https://loginproxy.gov.bc.ca/auth/realms/standard/.well-known/openid-configuration"
    clientId: <please-replace-me>
    clientSecret: <please-replace-me>
    claimName: "client_roles"
    scopes: "openid"
    redirectUri: "https://sso-minio.apps.gold.devops.gov.bc.ca/oauth_callback"
routes:
  minio:
    enabled: true
    host: sso-minio.apps.gold.devops.gov.bc.ca
