loki:
  write:
    replicas: 2
    persistence:
      size: 1Gi

  read:
    replicas: 1
    persistence:
      size: 1Gi

routes:
  minio:
    enabled: true
    host: sso-minio-sandbox.apps.gold.devops.gov.bc.ca
