loki:
  write:
    replicas: 3
    persistence:
      size: 1Gi
    resources:
      limits:
        cpu: 300m
        memory: 2Gi
      requests:
        cpu: 150m
        memory: 512Mi

  read:
    replicas: 3
    legacyReadTarget: true
    persistence:
      size: 1Gi
    resources:
      limits:
        cpu: 300m
        memory: 2Gi
      requests:
        cpu: 150m
        memory: 512Mi

  loki:
    storage:
      s3:
        accessKeyId: <please-replace-me>
        secretAccessKey: <please-replace-me>

    limits_config:
      retention_period: 4320h # 6 months

root-minio:
  enabled: true
  replicas: 3
  rootUser: <please-replace-me>
  rootPassword: <please-replace-me>
  persistence:
    size: 5Gi
  resources:
    limits:
      cpu: 450m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 512Mi
  oidc:
    configUrl: 'https://loginproxy.gov.bc.ca/auth/realms/standard/.well-known/openid-configuration'
    clientId: <please-replace-me>
    clientSecret: <please-replace-me>
    claimName: 'client_roles'
    scopes: 'openid'
    redirectUri: 'https://sso-minio.apps.gold.devops.gov.bc.ca/oauth_callback'
routes:
  minio:
    enabled: true
    host: sso-minio.apps.gold.devops.gov.bc.ca
