# see https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
loki:
  global:
    clusterDomain: "cluster.local"
    dnsService: "dns-default"
    dnsNamespace: "openshift-dns"

  nameOverride: sso-loki
  fullnameOverride: sso-loki
  imagePullSecrets: []

  loki:
    podSecurityContext:
    containerSecurityContext:
    auth_enabled: false

    storage:
      type: s3
      bucketNames:
        chunks: chunks
        ruler: ruler
        admin: admin
      s3:
        endpoint: sso-minio:9000
        bucketnames: chunks
        secretAccessKey: adminadmin
        accessKeyId: admin
        s3ForcePathStyle: true
        insecure: true

    schemaConfig:
      configs:
        - from: 2022-12-21
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 24h

    rulerConfig:
      storage:
        type: "s3"
        s3:
          bucketnames: ruler

    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/active
        shared_store: s3
        cache_location: /var/loki/cache
        cache_ttl: 24h

  serviceAccount:
    create: false

  test:
    enabled: false

  monitoring:
    dashboards:
      enabled: false

    rules:
      enabled: false

    serviceMonitor:
      enabled: false

    selfMonitoring:
      enabled: false

      grafanaAgent:
        installOperator: false

      lokiCanary:
        enabled: false

  write:
    replicas: 3
    persistence:
      size: 10Gi
      storageClass: netapp-block-standard
    resources:
      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 256Mi

  read:
    replicas: 3
    persistence:
      size: 10Gi
      storageClass: netapp-block-standard
    resources:
      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 256Mi

  ingress:
    enabled: false

  gateway:
    enabled: true
    replicas: 1
    podSecurityContext:
    resources:
      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 256Mi

  networkPolicy:
    enabled: false

# see https://github.com/minio/minio/blob/master/helm/minio/values.yaml
root-minio:
  enabled: true
  replicas: 2
  nameOverride: sso-minio
  fullnameOverride: sso-minio
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2023-01-02T09-40-09Z
  pullPolicy: IfNotPresent
  rootUser: admin
  rootPassword: adminadmin
  securityContext:
    enabled: false
  buckets:
    - name: chunks
      policy: none
      purge: false
    - name: ruler
      policy: none
      purge: false
    - name: admin
      policy: none
      purge: false
  persistence:
    size: 2Gi
    storageClass: netapp-block-standard
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 800Mi

  serviceAccount:
    create: false
  certsPath: /tmp/minio/certs/
  configPathmc: /tmp/minio/mc/

routes:
  minio:
    enabled: true
    host:
    serviceName: sso-minio-console
