version: '3.9'
services:
  aggregator:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true
    ports:
    - 8080:8080
    environment:
    - DB_HOSTNAME=postgres
    - DB_DATABASE=aggregation
    - DB_USERNAME=postgres
    - DB_PASSWORD=postgres
    depends_on:
    - postgres
  postgres:
    image: postgres:14.5
    volumes:
    - /var/lib/postgresql/data
    environment:
    - POSTGRES_DB=aggregation
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
