{
 "title": "Additional Settings - Clients who have override (Config)",
 "description": "This is the configuration setting",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "client.session.idle.timeout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client Session Idle aka Refresh",
   "type": "text",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 1 },
   "options": {
    "content": "*30 min STANDARD and Custom have their own*\r\n1. Review each environment and if the session values is smaller than the client values, set up time with the owners of the the integration to understand why\r\n2. Review each environment and if any of these settings are larger than 30 min STANDARD and Custom have their own, need to meet with the client.\r\n3. Keep your running notes in a text field for each env"
   }
  },
  {
   "title": "Dev",
   "type": "table",
   "description": "Client Session Idle(client.session.idle.timeout) - this setting is the time a client session is allowed to be idle before it expires. Tokens are invalidated when a client session is expired. If not set it uses the standard SSO session idle value.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select c.realm_id, c.client_id,ca.value client_idle_timeout, r.sso_idle_timeout\r\nFROM  client_attributes ca, client c, realm r\r\nWHERE c.id = ca.client_id\r\nand c.realm_id = r.id\r\nAND ca.name = 'client.session.idle.timeout'\r\nORDER BY ca.value DESC"
    }
   ]
  },
  {
   "title": "Dev",
   "type": "stat",
   "description": "Client Session Idle(client.session.idle.timeout) - this setting is the time a client session is allowed to be idle before it expires. Tokens are invalidated when a client session is expired. If not set it uses the standard SSO session idle value.",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  count(*)\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND ca.name = 'client.session.idle.timeout'\r\n"
    }
   ]
  },
  {
   "title": "DEV Client Session Idle aka Refresh",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 5 },
   "options": {
    "content": "Feb 8, 2024: No need to enage with any clients. all looking valid"
   }
  },
  {
   "title": "Test",
   "type": "table",
   "description": "Client Session Idle(client.session.idle.timeout) - this setting is the time a client session is allowed to be idle before it expires. Tokens are invalidated when a client session is expired. If not set it uses the standard SSO session idle value.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select c.realm_id, c.client_id,ca.value client_idle_timeout, sso_idle_timeout\r\nFROM  client_attributes ca, client c, realm r\r\nWHERE c.id = ca.client_id\r\nand c.realm_id = r.id\r\nAND ca.name = 'client.session.idle.timeout'\r\nORDER BY ca.value DESC"
    }
   ]
  },
  {
   "title": "Test",
   "type": "stat",
   "description": "Client Session Idle(client.session.idle.timeout) - this setting is the time a client session is allowed to be idle before it expires. Tokens are invalidated when a client session is expired. If not set it uses the standard SSO session idle value.",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  count(*)\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND ca.name = 'client.session.idle.timeout'\r\n"
    }
   ]
  },
  {
   "title": "TEST Client Session Idle aka Refresh",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 12 },
   "options": {
    "content": "Feb 8, 2024: No need to enage with any clients. all looking valid"
   }
  },
  {
   "title": "Prod",
   "type": "table",
   "description": "Client Session Idle(client.session.idle.timeout) - this setting is the time a client session is allowed to be idle before it expires. Tokens are invalidated when a client session is expired. If not set it uses the standard SSO session idle value.",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select c.realm_id, c.client_id,ca.value client_idle_timeout, sso_idle_timeout\r\nFROM  client_attributes ca, client c, realm r\r\nWHERE c.id = ca.client_id\r\nand c.realm_id = r.id\r\nAND ca.name = 'client.session.idle.timeout'\r\nORDER BY ca.value DESC"
    }
   ]
  },
  {
   "title": "PROD",
   "type": "stat",
   "description": "Client Session Idle(client.session.idle.timeout) - this setting is the time a client session is allowed to be idle before it expires. Tokens are invalidated when a client session is expired. If not set it uses the standard SSO session idle value.",
   "gridPos": { "h": 10, "w": 5, "x": 11, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  count(*)\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND ca.name = 'client.session.idle.timeout'\r\n"
    }
   ]
  },
  {
   "title": "PROD Client Session Idle aka Refresh",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 16, "y": 20 },
   "options": {
    "content": "Feb 8, 2024: No need to enage with any clients. all looking valid"
   }
  },
  {
   "title": "client.session.max.lifespan'",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Session Max aka Refresh Max",
     "type": "text",
     "gridPos": { "h": 4, "w": 22, "x": 0, "y": 2 },
     "options": {
      "content": "Client Session MAX at the *realm level is 10hours*\r\n\r\n1. Review each environment and if the session values is smaller than the client values, set up time with the owners of the the integration to understand why"
     }
    },
    {
     "title": "Dev",
     "type": "table",
     "description": "Client Session Max(client.session.max.lifespan') - this setting is the max time for a client session before it expires. Tokens are invalidated when a client session is expired. If not set it uses the standard SSO session max value. D",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "select  c.realm_id, c.client_id,ca.value\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND ca.name = 'client.session.max.lifespan'\r\nORDER BY ca.value DESC\r\n"
      }
     ]
    },
    {
     "title": "Dev Client Session Max aka Max",
     "type": "text",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
     "options": {
      "content": "Feb 8, 2024: No need to enage with any clients. all looking valid"
     }
    },
    {
     "title": "Test",
     "type": "table",
     "description": "Client Session Max(client.session.max.lifespan') - this setting is the max time for a client session before it expires. Tokens are invalidated when a client session is expired. If not set it uses the standard SSO session max value. D",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "select  c.realm_id, c.client_id,ca.value\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND ca.name = 'client.session.max.lifespan'\r\nORDER BY ca.value DESC\r\n"
      }
     ]
    },
    {
     "title": "TEST Client Session Max aka Max",
     "type": "text",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "options": {
      "content": "Feb 8, 2024: need to talk to the mines digital team"
     }
    },
    {
     "title": "Prod",
     "type": "table",
     "description": "Client Session Max(client.session.max.lifespan') - this setting is the max time for a client session before it expires. Tokens are invalidated when a client session is expired. If not set it uses the standard SSO session max value. D",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "select  c.realm_id, c.client_id,ca.value\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND ca.name = 'client.session.max.lifespan'\r\nORDER BY ca.value DESC\r\n"
      }
     ]
    },
    {
     "title": "PROD Client Session Max aka Max",
     "type": "text",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
     "options": {
      "content": "Feb 8, 2024: need to talk to the mines digital team"
     }
    }
   ]
  },
  { "title": "OFFLINE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "client.offline.session.idle.timeout",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Offline Session",
     "type": "text",
     "gridPos": { "h": 4, "w": 22, "x": 0, "y": 4 },
     "options": {
      "content": "Offline Session at the *realm level is 30 days*\r\n\r\n1. Review each environment and if the value is smaller than the client values, set up time with the owners of the the integration to understand why"
     }
    },
    {
     "title": "Dev",
     "type": "table",
     "description": "Client Offline Session Idle (client.offline.session.idle.timeout) - this setting is the time that client offline session is allowed to be idle before it expires. Offline tokens are invalidated when a client offline session is expired. If not set it uses the offline session idle value.",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "select  c.realm_id, c.client_id,ca.value\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND ca.name = 'client.offline.session.idle.timeout'\r\n"
      }
     ]
    },
    {
     "title": "Dev Offline ",
     "type": "text",
     "gridPos": { "h": 5, "w": 6, "x": 9, "y": 8 },
     "options": {
      "content": "Feb 8, 2024: No need to enage with any clients. all looking valid"
     }
    },
    {
     "title": "Test",
     "type": "table",
     "description": "Client Offline Session Idle (client.offline.session.idle.timeout) - this setting is the time that client offline session is allowed to be idle before it expires. Offline tokens are invalidated when a client offline session is expired. If not set it uses the offline session idle value.",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "select  c.realm_id, c.client_id,ca.value\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND ca.name = 'client.offline.session.idle.timeout'\r\n"
      }
     ]
    },
    {
     "title": "TEST Offline ",
     "type": "text",
     "gridPos": { "h": 5, "w": 6, "x": 9, "y": 13 },
     "options": {
      "content": "Feb 8, 2024: No need to enage with any clients. all looking valid"
     }
    },
    {
     "title": "Prod",
     "type": "table",
     "description": "Client Offline Session Idle (client.offline.session.idle.timeout) - this setting is the time that client offline session is allowed to be idle before it expires. Offline tokens are invalidated when a client offline session is expired. If not set it uses the offline session idle value.",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "rawSql": "select  c.realm_id, c.client_id,ca.value\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND ca.name = 'client.offline.session.idle.timeout'\r\n"
      }
     ]
    },
    {
     "title": "Prod Offline ",
     "type": "text",
     "gridPos": { "h": 5, "w": 6, "x": 9, "y": 18 },
     "options": {
      "content": "Feb 8, 2024: No need to enage with any clients. all looking valid"
     }
    }
   ]
  },
  {
   "title": "client.offline.session.max.lifespan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Offline Session MAX",
     "type": "text",
     "gridPos": { "h": 4, "w": 22, "x": 0, "y": 5 },
     "options": {
      "content": "this is not enabled at the realm level\r\nas standard level, it will be live only as long as the setting the client configured"
     }
    },
    {
     "title": "Dev",
     "type": "table",
     "description": "Client Offline Session Max (client.offline.session.max.lifespan) - this setting is the max time before a client offline session is expired. Offline tokens are invalidate when a client offline session is expired. If not set, it uses the offline session max value",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "select  c.realm_id, c.client_id,ca.value\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND ca.name = 'client.offline.session.max.lifespan'\r\nORDER BY ca.value DESC"
      }
     ]
    },
    {
     "title": "Dev Offline Session MAX",
     "type": "text",
     "gridPos": { "h": 6, "w": 6, "x": 17, "y": 9 },
     "options": {
      "content": "Feb 8, 2024: no issues on current client settings"
     }
    },
    {
     "title": "Test",
     "type": "table",
     "description": "Client Offline Session Max (client.offline.session.max.lifespan) - this setting is the max time before a client offline session is expired. Offline tokens are invalidate when a client offline session is expired. If not set, it uses the offline session max value",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "select  c.realm_id, c.client_id,ca.value\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND ca.name = 'client.offline.session.max.lifespan'\r\nORDER BY ca.value DESC"
      }
     ]
    },
    {
     "title": "Test Offline Session MAX",
     "type": "text",
     "gridPos": { "h": 5, "w": 6, "x": 10, "y": 16 },
     "options": {
      "content": "Feb 8, 2024: no issues on current client settings"
     }
    },
    {
     "title": "Prod",
     "type": "table",
     "description": "Client Offline Session Max (client.offline.session.max.lifespan) - this setting is the max time before a client offline session is expired. Offline tokens are invalidate when a client offline session is expired. If not set, it uses the offline session max value",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "select  c.realm_id, c.client_id,ca.value\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND ca.name = 'client.offline.session.max.lifespan'\r\nORDER BY ca.value DESC"
      }
     ]
    },
    {
     "title": "Prod Offline Session MAX",
     "type": "text",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
     "options": {
      "content": "Feb 8, 2024: no issues on current client settings"
     }
    }
   ]
  },
  {
   "title": "ACCESS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  {
   "title": "access.token.lifespan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Access token notes",
     "type": "text",
     "gridPos": { "h": 4, "w": 22, "x": 0, "y": 36 },
     "options": {
      "content": "5 min STANDARD and Custom could have their own\r\n\r\nmds-bcmi-4587 - is set to 15 mins as per product team request. this is within their security/stra knowledge base. this is internal to gove only. zorin noting no issues Feb 15.2024\r\n\r\nconn-ccbc-portal- set to 8 hours. Feb 23 confirmed with client they have MISO approval and put this info intheir STRA. zorin noting no issues.\r\n\r\noes-wbc-dev  - workbces will look into this. as of april 25, 2024 this has been removed. "
     }
    },
    {
     "title": "Dev",
     "type": "table",
     "description": "Access Token Lifespan(access.token.lifespan) - This setting is for the max time before an access token is expired. The value is recommended to be short relative to the SSO timeout. Default set to 5 mins",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "select  c.realm_id,c.client_id,ca.value\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND ca.name = 'access.token.lifespan'\r\norder by c.realm_id asc\r\n\r\n\r\n"
      }
     ]
    },
    {
     "title": "Test",
     "type": "table",
     "description": "Access Token Lifespan(access.token.lifespan) - This setting is for the max time before an access token is expired. The value is recommended to be short relative to the SSO timeout. Default set to 5 mins",
     "gridPos": { "h": 6, "w": 8, "x": 6, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "select  c.realm_id,c.client_id,ca.value\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND ca.name = 'access.token.lifespan'\r\norder by c.realm_id asc"
      }
     ]
    },
    {
     "title": "Prod",
     "type": "table",
     "description": "Access Token Lifespan(access.token.lifespan) - This setting is for the max time before an access token is expired. The value is recommended to be short relative to the SSO timeout. Default set to 5 mins",
     "gridPos": { "h": 6, "w": 8, "x": 14, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "select  c.realm_id,c.client_id,ca.value\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND ca.name = 'access.token.lifespan'\r\nORDER BY ca.value DESC"
      }
     ]
    },
    {
     "title": "Dev Standard TOTAL",
     "type": "stat",
     "description": "Access Token Lifespan(access.token.lifespan) - This setting is for the max time before an access token is expired. The value is recommended to be short relative to the SSO timeout. Default set to 5 mins",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*),c.realm_id\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND c.realm_id = 'standard'\r\nAND ca.name = 'access.token.lifespan'\r\nGROUP BY c.realm_id"
      }
     ]
    },
    {
     "title": "Dev Custom TOTAL",
     "type": "stat",
     "description": "Access Token Lifespan(access.token.lifespan) - This setting is for the max time before an access token is expired. The value is recommended to be short relative to the SSO timeout. Default set to 5 mins",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*)\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND c.realm_id not in ('standard')\r\nAND ca.name = 'access.token.lifespan'\r\n"
      }
     ]
    },
    {
     "title": "TEST  Standard TOTAL",
     "type": "stat",
     "description": "Access Token Lifespan(access.token.lifespan) - This setting is for the max time before an access token is expired. The value is recommended to be short relative to the SSO timeout. Default set to 5 mins",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*),c.realm_id\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND c.realm_id = 'standard'\r\nAND ca.name = 'access.token.lifespan'\r\nGROUP BY c.realm_id"
      }
     ]
    },
    {
     "title": "TEST Custom TOTAL",
     "type": "stat",
     "description": "Access Token Lifespan(access.token.lifespan) - This setting is for the max time before an access token is expired. The value is recommended to be short relative to the SSO timeout. Default set to 5 mins",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count (*)\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND c.realm_id not in ('standard')\r\nAND ca.name = 'access.token.lifespan'\r\n"
      }
     ]
    },
    {
     "title": "PROD Standard TOTAL",
     "type": "stat",
     "description": "Access Token Lifespan(access.token.lifespan) - This setting is for the max time before an access token is expired. The value is recommended to be short relative to the SSO timeout. Default set to 5 mins",
     "gridPos": { "h": 4, "w": 3, "x": 14, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*),c.realm_id\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND c.realm_id = 'standard'\r\nAND ca.name = 'access.token.lifespan'\r\nGROUP BY c.realm_id"
      }
     ]
    },
    {
     "title": "PROD  Custom TOTAL",
     "type": "stat",
     "description": "Access Token Lifespan(access.token.lifespan) - This setting is for the max time before an access token is expired. The value is recommended to be short relative to the SSO timeout. Default set to 5 mins",
     "gridPos": { "h": 4, "w": 3, "x": 17, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count (*)\r\nFROM  client_attributes ca, client c\r\nWHERE c.id = ca.client_id\r\nAND c.realm_id not in ('standard')\r\nAND ca.name = 'access.token.lifespan'\r\n"
      }
     ]
    }
   ]
  }
 ]
}