{
 "title": "Clients who are using offline sessions",
 "description": "these are THE users counts currently (confirm description)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Background info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Offline Sessions",
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": {
      "content": "With our service, we capture two things:\n1. Active Sessions via the cron job process https://sso-grafana.apps.gold.devops.gov.bc.ca/d/edff7318-49f9-4cdd-a66c-11f49357c79e/active-sessions-and-sso-logs\n2. Additional session settings: configurable via SSO Admin access on the UI https://sso-grafana.apps.gold.devops.gov.bc.ca/d/oX8hrKNIz/0e57c30a-ae80-52a4-b096-3bb811322139?orgId=1\n3. Custom Query to view the current user sessions in keycloak this time (this dashboard) "
     }
    },
    {
     "title": "Our service/policy",
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "options": {
      "content": "Thinking at this time ( Jan 15, 2024)\r\n\r\nLet's keep in line with OCIO standards to be within 30 mins. This means for those clients having user sessions for more than 30 mins, we can build community relations (not necessarily be the police) and advise on best practices.\r\n\r\nthe way to see the offline sessions is to go in the keycloak db or ui for the client and go to the offline access. you can see the offline access, which is approx 30 days "
     }
    }
   ]
  },
  { "title": "STANDARD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 2 },
   "options": {
    "content": "\r\n\r\nApril 2024: \r\nOffline Max value will be set to 60 days. this will be a safe number for those clients below as we've already spoken to them. through the analysis over the last few months, no one is going past the 60 day mark zs\r\nFeb 13: \r\n1) settings changed for Roadsafety integraiton in dev/test. need to follow up next week on prod\r\n2) aps team will be looking to make their changes to remove the scope by end of week. follow up next week\r\n3) era-r-2-4534 - went into a deep sleep; handed over to an AMS team. due to limitation of angular library or needed better control of refresh token. Yossi will look into this and we should follow May.\r\n4) spd-screening-portal-4830 is not in production. Yossi and team can look at it right now. will be moving to an AG custom realm. Go live is in May. \r\n5) bc-data-catalogue-3863 - alan to investigate in remove the offline from scope\r\n6) dip-3830 - Justin and Aidan will work on it and get back\r\n7) hydrological-alerting-5261 - they are in dev mode only, fairly new. need to give time to see if it comes in test/prod\r\n\r\nFeb 8, 2024: plan to chat with standard service first.\r\n"
   }
  },
  { "title": "OfflineClientSessionAnalysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "DEV",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count (*),\r\n  MAX  (\"Client\".\"client_id\" ) As \"Client_ID\",\r\n  MAX (\"Client\".\"realm_id\") as \"Realm_ID\",\r\n  \"public\".\"offline_client_session\".\"client_id\" AS \"client_identifier\"\r\n\r\nFROM\r\n  \"public\".\"offline_client_session\"\r\n \r\nLEFT JOIN \"public\".\"client\" AS \"Client\" ON \"public\".\"offline_client_session\".\"client_id\" = \"Client\".\"id\" WHERE \"Client\".\"realm_id\" in ('standard')\r\n\r\ngroup by \"public\".\"offline_client_session\".\"client_id\"\r\norder by count (*) desc"
    }
   ]
  },
  {
   "title": "TEST",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count (*),\r\n  MAX  (\"Client\".\"client_id\" ) As \"Client_ID\",\r\n  MAX (\"Client\".\"realm_id\") as \"Realm_ID\",\r\n  \"public\".\"offline_client_session\".\"client_id\" AS \"client_identifier\"\r\n\r\nFROM\r\n  \"public\".\"offline_client_session\"\r\n \r\nLEFT JOIN \"public\".\"client\" AS \"Client\" ON \"public\".\"offline_client_session\".\"client_id\" = \"Client\".\"id\" WHERE \"Client\".\"realm_id\" in ('standard')\r\n\r\ngroup by \"public\".\"offline_client_session\".\"client_id\"\r\norder by count (*) desc"
    }
   ]
  },
  {
   "title": "PROD",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count (*),\r\n  MAX  (\"Client\".\"client_id\" ) As \"Client_ID\",\r\n  MAX (\"Client\".\"realm_id\") as \"Realm_ID\",\r\n  \"public\".\"offline_client_session\".\"client_id\" AS \"client_identifier\"\r\n\r\nFROM\r\n  \"public\".\"offline_client_session\"\r\n \r\nLEFT JOIN \"public\".\"client\" AS \"Client\" ON \"public\".\"offline_client_session\".\"client_id\" = \"Client\".\"id\" WHERE \"Client\".\"realm_id\" in ('standard')\r\n\r\ngroup by \"public\".\"offline_client_session\".\"client_id\"\r\norder by count (*) desc"
    }
   ]
  },
  {
   "title": "DEV offline like KC UI- USERS",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select c.client_id,ue.username, to_timestamp(u.created_on) as token_creation_date, to_timestamp(u.last_session_refresh) as last_time_refreshed, \r\ndate(now())-to_timestamp(u.created_on)  as token_age, to_timestamp(u.last_session_refresh) < to_timestamp(u.created_on) as is_refresh_smaller_than_created\r\nfrom offline_client_session of, client c, offline_user_session u, user_entity ue\r\nwhere ue.id = u.user_id AND of.client_id = c.id\r\nand of.user_session_id = u.user_session_id\r\nand c.realm_id in ('standard')\r\n\r\norder by u.created_on asc"
    }
   ]
  },
  {
   "title": "DEV offline refresh smaller than created",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "select c.client_id, count (*)\r\nfrom offline_client_session of, client c, offline_user_session u\r\nwhere of.client_id = c.id\r\nand of.user_session_id = u.user_session_id\r\nand c.realm_id in ('standard')\r\nand  to_timestamp(u.last_session_refresh) < to_timestamp(u.created_on) \r\ngroup by c.client_id\r\n\r\n"
    }
   ]
  },
  {
   "title": "DEV offline refresh biggerthan created",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 26 },
   "targets": [
    {
     "rawSql": "select c.client_id, count (*)\r\nfrom offline_client_session of, client c, offline_user_session u\r\nwhere of.client_id = c.id\r\nand of.user_session_id = u.user_session_id\r\nand c.realm_id in ('standard')\r\nand  to_timestamp(u.last_session_refresh) >= to_timestamp(u.created_on) \r\ngroup by c.client_id\r\n\r\n"
    }
   ]
  },
  {
   "title": "Offline User Session__realm_id ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Offline_client_sessions DEV",
     "type": "table",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT count(*) AS \"count\",\"Offline User Session\".\"realm_id\" AS \"realm_id\"\r\nFROM \"public\".\"offline_client_session\"\r\nLEFT JOIN \"public\".\"offline_user_session\" \"Offline User Session\" ON \"public\".\"offline_client_session\".\"user_session_id\" = \"Offline User Session\".\"user_session_id\" where \"Offline User Session\".\"realm_id\" IN ('standard')\r\nGROUP BY \"Offline User Session\".\"realm_id\"\r\nORDER BY \"Offline User Session\".\"realm_id\" ASC"
      }
     ]
    },
    {
     "title": "Offline_client_sessions TEST",
     "type": "table",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT \"Offline User Session\".\"realm_id\" AS \"realm_id\", count(*) AS \"count\"\r\nFROM \"public\".\"offline_client_session\"\r\nLEFT JOIN \"public\".\"offline_user_session\" \"Offline User Session\" ON \"public\".\"offline_client_session\".\"user_session_id\" = \"Offline User Session\".\"user_session_id\" WHERE \"Offline User Session\".\"realm_id\" IN ('standard')\r\nGROUP BY \"Offline User Session\".\"realm_id\"\r\nORDER BY \"Offline User Session\".\"realm_id\" ASC"
      }
     ]
    },
    {
     "title": "Offline_client_sessions PROD",
     "type": "table",
     "gridPos": { "h": 4, "w": 8, "x": 12, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT \"Offline User Session\".\"realm_id\" AS \"realm_id\", count(*) AS \"count\"\r\nFROM \"public\".\"offline_client_session\"\r\nLEFT JOIN \"public\".\"offline_user_session\" \"Offline User Session\" ON \"public\".\"offline_client_session\".\"user_session_id\" = \"Offline User Session\".\"user_session_id\" WHERE \"Offline User Session\".\"realm_id\" IN ('standard')\r\nGROUP BY \"Offline User Session\".\"realm_id\"\r\nORDER BY \"Offline User Session\".\"realm_id\" ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "offline_user_session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "DEV",
     "type": "table",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "select count (*), \"offline_user_session\".\"realm_id\" \r\nFROM \"public\".\"offline_user_session\"\r\nwhere \"offline_user_session\".\"realm_id\" in ('standard')\r\nGROUP BY \"offline_user_session\".\"realm_id\" \r\nORDER BY \"offline_user_session\".\"realm_id\"  ASC"
      }
     ]
    },
    {
     "title": "TEST",
     "type": "table",
     "gridPos": { "h": 4, "w": 5, "x": 6, "y": 7 },
     "targets": [
      {
       "rawSql": "select count (*), \"offline_user_session\".\"realm_id\" \r\nFROM \"public\".\"offline_user_session\"\r\nwhere \"offline_user_session\".\"realm_id\" in ('standard')\r\nGROUP BY \"offline_user_session\".\"realm_id\" \r\nORDER BY \"offline_user_session\".\"realm_id\"  ASC"
      }
     ]
    },
    {
     "title": "PROD",
     "type": "table",
     "gridPos": { "h": 4, "w": 6, "x": 11, "y": 7 },
     "targets": [
      {
       "rawSql": "select count (*), \"offline_user_session\".\"realm_id\" \r\nFROM \"public\".\"offline_user_session\"\r\nwhere \"offline_user_session\".\"realm_id\" in ('standard')\r\nGROUP BY \"offline_user_session\".\"realm_id\" \r\nORDER BY \"offline_user_session\".\"realm_id\"  ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "CUSTOM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true
  },
  {
   "title": "offline client sessions  - custom realms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notes",
     "type": "text",
     "gridPos": { "h": 5, "w": 21, "x": 0, "y": 7 },
     "options": {
      "content": "Feb 23 2024:\r\n\r\n\r\nDEVINT_SAJE_BCEID_BASIC - working session leo removed in dev.\r\n\r\noes-wbc-dev  - workbces branko will look into this. aim to follow up by end of march"
     }
    },
    {
     "title": "DEV",
     "type": "table",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  count (*),\r\n  MAX  (\"Client\".\"client_id\" ) As \"Client_ID\",\r\n  MAX (\"Client\".\"realm_id\") as \"Realm_ID\",\r\n  \"public\".\"offline_client_session\".\"client_id\" AS \"client_identifier\"\r\n\r\nFROM\r\n  \"public\".\"offline_client_session\"\r\n \r\nLEFT JOIN \"public\".\"client\" AS \"Client\" ON \"public\".\"offline_client_session\".\"client_id\" = \"Client\".\"id\" WHERE \"Client\".\"realm_id\" NOT IN ('standard')\r\n\r\ngroup by \"public\".\"offline_client_session\".\"client_id\"\r\norder by count (*) desc"
      }
     ]
    },
    {
     "title": "TEST",
     "type": "table",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  count (*),\r\n  MAX  (\"Client\".\"client_id\" ) As \"Client_ID\",\r\n  MAX (\"Client\".\"realm_id\") as \"Realm_ID\",\r\n  \"public\".\"offline_client_session\".\"client_id\" AS \"client_identifier\"\r\n\r\nFROM\r\n  \"public\".\"offline_client_session\"\r\n \r\nLEFT JOIN \"public\".\"client\" AS \"Client\" ON \"public\".\"offline_client_session\".\"client_id\" = \"Client\".\"id\" WHERE \"Client\".\"realm_id\" NOT IN ('standard')\r\n\r\ngroup by \"public\".\"offline_client_session\".\"client_id\"\r\norder by count (*) desc"
      }
     ]
    },
    {
     "title": "PROD",
     "type": "table",
     "gridPos": { "h": 7, "w": 7, "x": 14, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  count (*),\r\n  MAX  (\"Client\".\"client_id\" ) As \"Client_ID\",\r\n  MAX (\"Client\".\"realm_id\") as \"Realm_ID\",\r\n  \"public\".\"offline_client_session\".\"client_id\" AS \"client_identifier\"\r\n\r\nFROM\r\n  \"public\".\"offline_client_session\"\r\n \r\nLEFT JOIN \"public\".\"client\" AS \"Client\" ON \"public\".\"offline_client_session\".\"client_id\" = \"Client\".\"id\" WHERE \"Client\".\"realm_id\" NOT IN ('standard')\r\n\r\ngroup by \"public\".\"offline_client_session\".\"client_id\"\r\norder by count (*) desc"
      }
     ]
    }
   ]
  },
  {
   "title": "offline user sessions__realmID - custom realm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Offline_client_sessions DEV",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT count(*) AS \"count\",\"Offline User Session\".\"realm_id\" AS \"realm_id\"\r\nFROM \"public\".\"offline_client_session\"\r\nLEFT JOIN \"public\".\"offline_user_session\" \"Offline User Session\" ON \"public\".\"offline_client_session\".\"user_session_id\" = \"Offline User Session\".\"user_session_id\" \r\nwhere \"Offline User Session\".\"realm_id\" NOT IN ('standard')\r\nGROUP BY \"Offline User Session\".\"realm_id\"\r\nORDER BY count(*) desc"
      }
     ]
    },
    {
     "title": "Offline_client_sessions TEST",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT count(*) AS \"count\",\"Offline User Session\".\"realm_id\" AS \"realm_id\"\r\nFROM \"public\".\"offline_client_session\"\r\nLEFT JOIN \"public\".\"offline_user_session\" \"Offline User Session\" ON \"public\".\"offline_client_session\".\"user_session_id\" = \"Offline User Session\".\"user_session_id\" \r\nwhere \"Offline User Session\".\"realm_id\" NOT IN ('standard')\r\nGROUP BY \"Offline User Session\".\"realm_id\"\r\nORDER BY count(*) desc"
      }
     ]
    },
    {
     "title": "Offline_client_sessions PROD",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT count(*) AS \"count\",\"Offline User Session\".\"realm_id\" AS \"realm_id\"\r\nFROM \"public\".\"offline_client_session\"\r\nLEFT JOIN \"public\".\"offline_user_session\" \"Offline User Session\" ON \"public\".\"offline_client_session\".\"user_session_id\" = \"Offline User Session\".\"user_session_id\" \r\nwhere \"Offline User Session\".\"realm_id\" NOT IN ('standard')\r\nGROUP BY \"Offline User Session\".\"realm_id\"\r\nORDER BY count(*) desc"
      }
     ]
    }
   ]
  },
  {
   "title": "offline user sessions custom realms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "DEV",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "select count (*), \"offline_user_session\".\"realm_id\" \r\nFROM \"public\".\"offline_user_session\"\r\nwhere \"offline_user_session\".\"realm_id\" NOT IN ('standard')\r\nGROUP BY \"offline_user_session\".\"realm_id\" \r\nORDER BY count (*) DESC"
      }
     ]
    },
    {
     "title": "TEST",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "targets": [
      {
       "rawSql": "select count (*), \"offline_user_session\".\"realm_id\" \r\nFROM \"public\".\"offline_user_session\"\r\nwhere \"offline_user_session\".\"realm_id\" NOT IN ('standard')\r\nGROUP BY \"offline_user_session\".\"realm_id\" \r\nORDER BY count (*) DESC"
      }
     ]
    },
    {
     "title": "PROD",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
     "targets": [
      {
       "rawSql": "select count (*), \"offline_user_session\".\"realm_id\" \r\nFROM \"public\".\"offline_user_session\"\r\nwhere \"offline_user_session\".\"realm_id\" NOT IN ('standard')\r\nGROUP BY \"offline_user_session\".\"realm_id\" \r\nORDER BY count (*) DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "Nice to know for SSO team",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "DEV first time used by client",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "rawSql": "select c.client_id, c.realm_id, min(to_timestamp((of.data::json -> 'notes' ->> 'startedAt')::bigint)) as first_time_client_ever_created_token\r\nfrom offline_client_session of, client c\r\nwhere of.client_id = c.id\r\ngroup by c.client_id, c.realm_id\r\norder by first_time_client_ever_created_token asc"
      }
     ]
    }
   ]
  }
 ]
}