{
 "title": "Custom Service Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Protocol Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dev Protocol",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  \"public\".\"client\".\"protocol\" AS \"protocol\",\r\n  COUNT(*) AS \"count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  \"public\".\"client\".\"realm_id\" not in ( 'standard','idir','azureidir','bceidbusiness','bceidboth','github','master','bceidbasic')\r\n  AND  (\"public\".\"client\".\"client_id\" not in ('account', 'account-console','admin-cli','broker','realm-management','security-admin-console'  ))\r\nGROUP BY\r\n  \"public\".\"client\".\"protocol\"\r\nORDER BY\r\n  \"public\".\"client\".\"protocol\" ASC"
      }
     ]
    },
    {
     "title": "Test Protocol",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 6, "x": 7, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  \"public\".\"client\".\"protocol\" AS \"protocol\",\r\n  COUNT(*) AS \"count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  \"public\".\"client\".\"realm_id\" not in ( 'standard','idir','azureidir','bceidbusiness','bceidboth','github','master','bceidbasic')\r\n  AND  (\"public\".\"client\".\"client_id\" not in ('account', 'account-console','admin-cli','broker','realm-management','security-admin-console'  ))\r\nGROUP BY\r\n  \"public\".\"client\".\"protocol\"\r\nORDER BY\r\n  \"public\".\"client\".\"protocol\" ASC"
      }
     ]
    },
    {
     "title": "Prod Protocol",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 6, "x": 13, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  \"public\".\"client\".\"protocol\" AS \"protocol\",\r\n  COUNT(*) AS \"count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  \"public\".\"client\".\"realm_id\" not in ( 'standard','idir','azureidir','bceidbusiness','bceidboth','github','master','bceidbasic')\r\n  AND  (\"public\".\"client\".\"client_id\" not in ('account', 'account-console','admin-cli','broker','realm-management','security-admin-console'  ))\r\nGROUP BY\r\n  \"public\".\"client\".\"protocol\"\r\nORDER BY\r\n  \"public\".\"client\".\"protocol\" ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Realms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "DEV Custom Realms",
     "type": "stat",
     "description": "does not include standard and idp (parent) realms",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\r\nselect count(*) \r\nfrom realm where realm.name not in ('idir','azureidir','bceidbusiness','bceidboth','github','master','bceidbasic','standard')"
      }
     ]
    },
    {
     "title": "TEST Custom Realms",
     "type": "stat",
     "description": "does not include standard and parent realms",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\r\nselect count(*) \r\nfrom realm where realm.name not in ('idir','azureidir','bceidbusiness','bceidboth','github','master','bceidbasic','standard')"
      }
     ]
    },
    {
     "title": "PROD Custom Realms",
     "type": "stat",
     "description": "does not include standard and idp parent realms",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\r\nselect count(*) \r\nfrom realm where realm.name not in ('idir','azureidir','bceidbusiness','bceidboth','github','master','bceidbasic','standard')"
      }
     ]
    },
    {
     "title": "Prod  Realm Names",
     "type": "table",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 10 },
     "targets": [
      {
       "rawSql": "select realm.id\r\nfrom realm where realm.name not in ('idir','azureidir','bceidbusiness','bceidboth','github','master','bceidbasic','standard')"
      }
     ]
    }
   ]
  },
  {
   "title": "Avg Number of Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dev Avg Clients",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  AVG(\"source\".\"count\") AS \"avg\"\r\nFROM\r\n  (\r\n    SELECT\r\n      \"public\".\"client\".\"realm_id\" AS \"realm_id\",\r\n      COUNT(*) AS \"count\"\r\n    FROM\r\n      \"public\".\"client\"\r\n   \r\nWHERE\r\n      (\r\n        (\r\n          \"public\".\"client\".\"realm_id\" not in (\r\n            'standard',\r\n            'idir',\r\n            'azureidir',\r\n            'bceidbusiness',\r\n            'bceidboth',\r\n            'github',\r\n            'master',\r\n            'bceidbasic'\r\n          )\r\n        )\r\n       \r\n    OR (\"public\".\"client\".\"realm_id\" IS NULL)\r\n      )\r\n     \r\n   AND (\r\n        (\"public\".\"client\".\"client_id\" <> 'account')\r\n        OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n        OR (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n        OR (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n        OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n        OR (\"public\".\"client\".\"client_id\" <> 'broker')\r\n        OR (\r\n          \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n        )\r\n        OR (\r\n          \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n        )\r\n      )\r\n   \r\nGROUP BY\r\n      \"public\".\"client\".\"realm_id\"\r\n   \r\nORDER BY\r\n      count desc\r\n  ) AS \"source\""
      }
     ]
    },
    {
     "title": "Test Avg Clients",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  AVG(\"source\".\"count\") AS \"avg\"\r\nFROM\r\n  (\r\n    SELECT\r\n      \"public\".\"client\".\"realm_id\" AS \"realm_id\",\r\n      COUNT(*) AS \"count\"\r\n    FROM\r\n      \"public\".\"client\"\r\n   \r\nWHERE\r\n      (\r\n        (\r\n          \"public\".\"client\".\"realm_id\" not in (\r\n            'standard',\r\n            'idir',\r\n            'azureidir',\r\n            'bceidbusiness',\r\n            'bceidboth',\r\n            'github',\r\n            'master',\r\n            'bceidbasic'\r\n          )\r\n        )\r\n       \r\n    OR (\"public\".\"client\".\"realm_id\" IS NULL)\r\n      )\r\n     \r\n   AND (\r\n        (\"public\".\"client\".\"client_id\" <> 'account')\r\n        OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n        OR (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n        OR (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n        OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n        OR (\"public\".\"client\".\"client_id\" <> 'broker')\r\n        OR (\r\n          \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n        )\r\n        OR (\r\n          \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n        )\r\n      )\r\n   \r\nGROUP BY\r\n      \"public\".\"client\".\"realm_id\"\r\n   \r\nORDER BY\r\n      count desc\r\n  ) AS \"source\""
      }
     ]
    },
    {
     "title": "Prod Avg Clients",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  AVG(\"source\".\"count\") AS \"avg\"\r\nFROM\r\n  (\r\n    SELECT\r\n      \"public\".\"client\".\"realm_id\" AS \"realm_id\",\r\n      COUNT(*) AS \"count\"\r\n    FROM\r\n      \"public\".\"client\"\r\n   \r\nWHERE\r\n      (\r\n        (\r\n          \"public\".\"client\".\"realm_id\" not in (\r\n            'standard',\r\n            'idir',\r\n            'azureidir',\r\n            'bceidbusiness',\r\n            'bceidboth',\r\n            'github',\r\n            'master',\r\n            'bceidbasic'\r\n          )\r\n        )\r\n       \r\n    OR (\"public\".\"client\".\"realm_id\" IS NULL)\r\n      )\r\n     \r\n   AND (\r\n        (\"public\".\"client\".\"client_id\" <> 'account')\r\n        OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n        OR (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n        OR (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n        OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n        OR (\"public\".\"client\".\"client_id\" <> 'broker')\r\n        OR (\r\n          \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n        )\r\n        OR (\r\n          \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n        )\r\n      )\r\n   \r\nGROUP BY\r\n      \"public\".\"client\".\"realm_id\"\r\n   \r\nORDER BY\r\n      count desc\r\n  ) AS \"source\""
      }
     ]
    }
   ]
  },
  {
   "title": "Avg Number of Service Accounts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dev Service Accounts Avg",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  AVG(\"source\".\"count\") AS \"avg\"\r\nFROM\r\n  (\r\n    SELECT\r\n      \"public\".\"client\".\"realm_id\" AS \"realm_id\",\r\n      count(*) AS \"count\"\r\n    FROM\r\n      \"public\".\"client\"\r\n   \r\nWHERE\r\n      (\r\n        \"public\".\"client\".\"realm_id\" not in (\r\n          'standard',\r\n          'idir',\r\n          'azureidir',\r\n          'bceidbusiness',\r\n          'bceidboth',\r\n          'github',\r\n          'master',\r\n          'bceidbasic'\r\n        )\r\n       \r\n   AND \"public\".\"client\".\"service_accounts_enabled\" = TRUE\r\n      )\r\n   \r\nGROUP BY\r\n      \"public\".\"client\".\"realm_id\"\r\n   \r\nORDER BY\r\n      count desc\r\n  ) AS \"source\""
      }
     ]
    },
    {
     "title": "Test Service Accounts Avg",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  AVG(\"source\".\"count\") AS \"avg\"\r\nFROM\r\n  (\r\n    SELECT\r\n      \"public\".\"client\".\"realm_id\" AS \"realm_id\",\r\n      count(*) AS \"count\"\r\n    FROM\r\n      \"public\".\"client\"\r\n   \r\nWHERE\r\n      (\r\n        \"public\".\"client\".\"realm_id\" not in (\r\n          'standard',\r\n          'idir',\r\n          'azureidir',\r\n          'bceidbusiness',\r\n          'bceidboth',\r\n          'github',\r\n          'master',\r\n          'bceidbasic'\r\n        )\r\n       \r\n   AND \"public\".\"client\".\"service_accounts_enabled\" = TRUE\r\n      )\r\n   \r\nGROUP BY\r\n      \"public\".\"client\".\"realm_id\"\r\n   \r\nORDER BY\r\n      count desc\r\n  ) AS \"source\""
      }
     ]
    },
    {
     "title": "Service Accounts Avg",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  AVG(\"source\".\"count\") AS \"avg\"\r\nFROM\r\n  (\r\n    SELECT\r\n      \"public\".\"client\".\"realm_id\" AS \"realm_id\",\r\n      count(*) AS \"count\"\r\n    FROM\r\n      \"public\".\"client\"\r\n   \r\nWHERE\r\n      (\r\n        \"public\".\"client\".\"realm_id\" not in (\r\n          'standard',\r\n          'idir',\r\n          'azureidir',\r\n          'bceidbusiness',\r\n          'bceidboth',\r\n          'github',\r\n          'master',\r\n          'bceidbasic'\r\n        )\r\n       \r\n   AND \"public\".\"client\".\"service_accounts_enabled\" = TRUE\r\n      )\r\n   \r\nGROUP BY\r\n      \"public\".\"client\".\"realm_id\"\r\n   \r\nORDER BY\r\n      count desc\r\n  ) AS \"source\""
      }
     ]
    }
   ]
  },
  {
   "title": "BCSC integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true
  },
  {
   "title": "BC Services Card in  custom realm",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "options": {
    "content": "# Context\n\nLeadership and IDIM partners may want to know how many custom realms have bc services card as an integration. THis section shows this as we currently do not offer a BCSC integration in our standard service."
   }
  },
  {
   "title": "Average Number of realms with  BCSC",
   "type": "stat",
   "description": "across envs",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(distinct realm.name) AS \"Dev Count\"\r\nFROM\r\n  \"public\".\"identity_provider_mapper\"\r\n \r\nLEFT JOIN realm ON identity_provider_mapper.realm_id = realm.id\r\nWHERE\r\nLOWER(\"public\".\"identity_provider_mapper\".\"idp_alias\") LIKE '%bcsc%'\r\n  OR    LOWER(\"public\".\"identity_provider_mapper\".\"idp_alias\") LIKE '%services%'\r\n"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(distinct realm.name) AS \"Test Count\"\r\nFROM\r\n  \"public\".\"identity_provider_mapper\"\r\n \r\nLEFT JOIN realm ON identity_provider_mapper.realm_id = realm.id\r\nWHERE\r\nLOWER(\"public\".\"identity_provider_mapper\".\"idp_alias\") LIKE '%bcsc%'\r\n  OR    LOWER(\"public\".\"identity_provider_mapper\".\"idp_alias\") LIKE '%services%'"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(distinct realm.name) AS \"Prod Count\"\r\nFROM\r\n  \"public\".\"identity_provider_mapper\"\r\n \r\nLEFT JOIN realm ON identity_provider_mapper.realm_id = realm.id\r\nWHERE\r\nLOWER(\"public\".\"identity_provider_mapper\".\"idp_alias\") LIKE '%bcsc%'\r\n  OR    LOWER(\"public\".\"identity_provider_mapper\".\"idp_alias\") LIKE '%services%'"
    }
   ]
  },
  {
   "title": "BCSC JWK url (adjust query for URL)",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 15, "y": 5 },
   "targets": [
    {
     "rawSql": "\r\nselect  ip.realm_id, ipc.value\r\nfrom identity_provider as ip, identity_provider_config  as  ipc where ipc.identity_provider_id=ip.internal_id\r\n AND  (ip.provider_alias like '%bcsc%' OR ip.provider_alias like  '%services%' OR ip.provider_alias like '%bcsc-mobile%')\r\nAND  ipc.name ='jwksUrl'\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Dev BCSC",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\ndistinct \"Realm\".\"name\" AS \"Realm__name\"\r\n \r\nFROM\r\n  \"public\".\"identity_provider_mapper\"\r\n \r\nLEFT JOIN \"public\".\"realm\" AS \"Realm\" ON \"public\".\"identity_provider_mapper\".\"realm_id\" = \"Realm\".\"id\"\r\nWHERE\r\n  LOWER(\"public\".\"identity_provider_mapper\".\"idp_alias\") LIKE '%bcsc-mobile%'\r\n  OR    LOWER(\"public\".\"identity_provider_mapper\".\"idp_alias\") LIKE '%bcsc%'\r\n  OR    LOWER(\"public\".\"identity_provider_mapper\".\"idp_alias\") LIKE '%services%'\r\n"
    }
   ]
  },
  {
   "title": "Test BCSC",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 5, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\ndistinct \"Realm\".\"name\" AS \"Realm__name\"\r\n \r\nFROM\r\n  \"public\".\"identity_provider_mapper\"\r\n \r\nLEFT JOIN \"public\".\"realm\" AS \"Realm\" ON \"public\".\"identity_provider_mapper\".\"realm_id\" = \"Realm\".\"id\"\r\nWHERE\r\n  LOWER(\"public\".\"identity_provider_mapper\".\"idp_alias\") LIKE '%bcsc-mobile%'\r\n  OR    LOWER(\"public\".\"identity_provider_mapper\".\"idp_alias\") LIKE '%bcsc%'\r\n  OR    LOWER(\"public\".\"identity_provider_mapper\".\"idp_alias\") LIKE '%services%'\r\n"
    }
   ]
  },
  {
   "title": "Prod BCSC",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 10, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\ndistinct \"Realm\".\"name\" AS \"Realm__name\"\r\n \r\nFROM\r\n  \"public\".\"identity_provider_mapper\"\r\n \r\nLEFT JOIN \"public\".\"realm\" AS \"Realm\" ON \"public\".\"identity_provider_mapper\".\"realm_id\" = \"Realm\".\"id\"\r\nWHERE\r\n  LOWER(\"public\".\"identity_provider_mapper\".\"idp_alias\") LIKE '%bcsc-mobile%'\r\n  OR    LOWER(\"public\".\"identity_provider_mapper\".\"idp_alias\") LIKE '%bcsc%'\r\n  OR    LOWER(\"public\".\"identity_provider_mapper\".\"idp_alias\") LIKE '%services%'\r\n"
    }
   ]
  },
  {
   "title": "Realms using legacy redirect uri",
   "type": "table",
   "description": "Realms in dev who have set the legacy redirect uri parameter to true in some idp",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "select realm_id from identity_provider_config join identity_provider on identity_provider_config.identity_provider_id = identity_provider.internal_id where name ilike '%redirect%' and value='true' limit 10;"
    }
   ]
  },
  {
   "title": "BCSC with Roles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true
  },
  {
   "title": "DEV BCSC Using roles",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "select c1.realm_id, count (kr.name) \r\nfrom client c1, keycloak_role kr\r\nwhere  kr.client = c1.id\r\nand c1.realm_id NOT LIKE 'standard'\r\nAND c1.realm_id IN ( select r.name from realm r, identity_provider_mapper ipm where  ipm.realm_id=r.id AND (LOWER(ipm.\"idp_alias\") LIKE '%bcsc-mobile%'   OR    LOWER(ipm.\"idp_alias\") LIKE '%bcsc%'   OR    LOWER(ipm.\"idp_alias\") LIKE '%services%') )\r\ngroup by c1.realm_id\r\n"
    }
   ]
  },
  {
   "title": "TEST BCSC Using roles",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 5, "y": 34 },
   "targets": [
    {
     "rawSql": "select c1.realm_id, count (kr.name) \r\nfrom client c1, keycloak_role kr\r\nwhere  kr.client = c1.id\r\nand c1.realm_id NOT LIKE 'standard'\r\nAND c1.realm_id IN ( select r.name from realm r, identity_provider_mapper ipm where  ipm.realm_id=r.id AND (LOWER(ipm.\"idp_alias\") LIKE '%bcsc-mobile%'   OR    LOWER(ipm.\"idp_alias\") LIKE '%bcsc%'   OR    LOWER(ipm.\"idp_alias\") LIKE '%services%') )\r\ngroup by c1.realm_id\r\n"
    }
   ]
  },
  {
   "title": "PROD BCSC Using roles",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 10, "y": 34 },
   "targets": [
    {
     "rawSql": "select c1.realm_id, count (kr.name) \r\nfrom client c1, keycloak_role kr\r\nwhere  kr.client = c1.id\r\nand c1.realm_id NOT LIKE 'standard'\r\nAND c1.realm_id IN ( select r.name from realm r, identity_provider_mapper ipm where  ipm.realm_id=r.id AND (LOWER(ipm.\"idp_alias\") LIKE '%bcsc-mobile%'   OR    LOWER(ipm.\"idp_alias\") LIKE '%bcsc%'   OR    LOWER(ipm.\"idp_alias\") LIKE '%services%') )\r\ngroup by c1.realm_id\r\n"
    }
   ]
  }
 ]
}