{
 "title": "SSO Environment and IDP Analysis",
 "description": "This is for all standard clients",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_POSTGRES", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Environment",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# ${DS_POSTGRES} environment\n\nCurrently showing IDP information for ${DS_POSTGRES}. Toggle the variable in the top left to switch between environments."
   }
  },
  {
   "title": "Count of clients by IDPs",
   "type": "barchart",
   "description": "Breakdown of clients for each IDP. Note none stands for service account",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "WITH standard_clients as (\r\n  SELECT\r\n    *\r\n  FROM\r\n    \"public\".\"client\"\r\n  WHERE\r\n    (\"public\".\"client\".\"realm_id\" = 'standard')\r\n  \r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'account')\r\n    \r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'broker')\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\r\n        \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n      )\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\r\n        \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n      )\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      \"public\".\"client\".\"description\" = 'CSS App Created'\r\n    )\r\n  ),\r\n  all_clients_and_idps as (\r\n    SELECT standard_clients.client_id, client_scope.name FROM standard_clients join client_scope_client on standard_clients.id = client_scope_client.client_id join client_scope on client_scope.id = client_scope_client.scope_id \r\n    where client_scope.name in ('idir', 'bceidbasic', 'bceidboth', 'bceidbusiness', 'azureidir', 'githubbcgov', 'githubpublic', 'idir-saml', 'bceidbasic-saml', 'bceidboth-saml', 'bceidbusiness-saml', 'azureidir-saml', 'githubbcgov-saml', 'githubpublic-saml', 'bcsc') \r\n    OR client_scope.name LIKE 'bcsc%'\r\n    order by client_id\r\n  ),\r\n  clients_without_idps as (\r\n    select count(client_id) as no_idp_count from standard_clients t1 where not exists (\r\n      select client_id from all_clients_and_idps where client_id = t1.client_id\r\n    )\r\n  )\r\n  select name, count(client_id) as clients from all_clients_and_idps group by name UNION select 'none' as name, no_idp_count as clients from clients_without_idps order by name, clients desc;\r\n\r\n"
    }
   ]
  },
  {
   "title": "List of Clients With IDPs",
   "type": "table",
   "description": "A list of all clients and their aggregated IDPs",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "WITH standard_clients as (\r\n  SELECT\r\n    *\r\n  FROM\r\n    \"public\".\"client\"\r\n  WHERE\r\n    (\"public\".\"client\".\"realm_id\" = 'standard')\r\n  \r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'account')\r\n    \r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'broker')\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\r\n        \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n      )\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\r\n        \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n      )\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      \"public\".\"client\".\"description\" = 'CSS App Created'\r\n    )\r\n  ),\r\n  all_clients_and_idps as (\r\n    SELECT standard_clients.client_id, client_scope.name FROM standard_clients join client_scope_client on standard_clients.id = client_scope_client.client_id join client_scope on client_scope.id = client_scope_client.scope_id \r\n    where client_scope.name in ('idir', 'bceidbasic', 'bceidboth', 'bceidbusiness', 'azureidir', 'githubbcgov', 'githubpublic', 'idir-saml', 'bceidbasic-saml', 'bceidboth-saml', 'bceidbusiness-saml', 'azureidir-saml', 'githubbcgov-saml', 'githubpublic-saml','bcsc') order by client_id\r\n  )\r\n  select client_id, array_agg(name) as IDP_List from all_clients_and_idps group by client_id order by client_id;"
    }
   ]
  },
  {
   "title": "List of Clients With No IDPs",
   "type": "table",
   "description": "Clients without an IDP client scope assigned. Should be service or team accounts.",
   "gridPos": { "h": 9, "w": 8, "x": 10, "y": 13 },
   "targets": [
    {
     "rawSql": "WITH standard_clients as (\r\n  SELECT\r\n    *\r\n  FROM\r\n    \"public\".\"client\"\r\n  WHERE\r\n    (\"public\".\"client\".\"realm_id\" = 'standard')\r\n  \r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'account')\r\n    \r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'broker')\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\r\n        \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n      )\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\r\n        \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n      )\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      \"public\".\"client\".\"description\" = 'CSS App Created'\r\n    )\r\n  ),\r\n  all_clients_and_idps as (\r\n    SELECT standard_clients.client_id, client_scope.name FROM standard_clients join client_scope_client on standard_clients.id = client_scope_client.client_id join client_scope on client_scope.id = client_scope_client.scope_id \r\n    where client_scope.name in ('idir', 'bceidbasic', 'bceidboth', 'bceidbusiness', 'azureidir', 'githubbcgov', 'githubpublic', 'idir-saml', 'bceidbasic-saml', 'bceidboth-saml', 'bceidbusiness-saml', 'azureidir-saml', 'githubbcgov-saml', 'githubpublic-saml') order by client_id\r\n  )\r\n  select client_id from standard_clients t1 where not exists (\r\n    select client_id from all_clients_and_idps where client_id = t1.client_id\r\n  )\r\n  "
    }
   ]
  },
  {
   "title": "Client IDP intersection Count",
   "type": "stat",
   "description": "This query counts the intersection of IDPs to get the number of repeat clients. E.g. a client with three IDPs would add 2 to this count. It is a sanity check on the math to double check the sum of IDP's less this number is the same as total clients.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH standard_clients as (\r\n  SELECT\r\n    *\r\n  FROM\r\n    \"public\".\"client\"\r\n  WHERE\r\n    (\"public\".\"client\".\"realm_id\" = 'standard')\r\n  \r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'account')\r\n    \r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\"public\".\"client\".\"client_id\" <> 'broker')\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\r\n        \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n      )\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      (\r\n        \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n      )\r\n      OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n    )\r\n    AND (\r\n      \"public\".\"client\".\"description\" = 'CSS App Created'\r\n    )\r\n  ),\r\n  all_clients_and_idps as (\r\n    SELECT standard_clients.client_id, client_scope.name FROM standard_clients join client_scope_client on standard_clients.id = client_scope_client.client_id join client_scope on client_scope.id = client_scope_client.scope_id \r\n    where client_scope.name in ('idir', 'bceidbasic', 'bceidboth', 'bceidbusiness', 'azureidir', 'githubbcgov', 'githubpublic', 'idir-saml', 'bceidbasic-saml', 'bceidboth-saml', 'bceidbusiness-saml', 'azureidir-saml', 'githubbcgov-saml', 'githubpublic-saml') order by client_id\r\n  ),\r\n  -- distinct_clients as (\r\n  --   select distinct client_id from all_clients_and_idps group by client_id\r\n  -- ) select count(*) from distinct_clients\r\n  counts as (\r\n    select count(client_id) - 1 as count from all_clients_and_idps group by client_id having count(client_id) > 1 order by client_id\r\n  ) select sum(count) from counts\r\n  -- select client_id, array_agg(name) from all_clients_and_idps group by client_id having count(client_id) > 1 order by client_id;\r\n"
    }
   ]
  }
 ]
}