name: Publish SSO Promtail Instances

on:
  push:
    branches:
    - main
    - dev
    paths:
    - helm/promtail-aggregator/**
    - helm/promtail-loki/**
    - .github/workflows/deploy-promtail.yaml

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Set env to Sandbox
      if: (github.ref == 'refs/heads/dev' && github.event_name == 'push')
      run: |
        cat >> $GITHUB_ENV <<EOF
        OPENSHIFT_TOKEN=${{ secrets.SANDBOX_OPENSHIFT_TOKEN }}
        OPENSHIFT_SERVER=${{ secrets.SANDBOX_OPENSHIFT_SERVER }}
        OPENSHIFT_NAMESPACE=e4ca1d
        ${{ secrets.GRAFANA_SANDBOX_ENV }}
        EOF

    - name: Set env to Production
      if: (github.ref == 'refs/heads/main' && github.event_name == 'push')
      run: |
        cat >> $GITHUB_ENV <<EOF
        OPENSHIFT_TOKEN=${{ secrets.PROD_OPENSHIFT_TOKEN }}
        OPENSHIFT_SERVER=${{ secrets.PROD_OPENSHIFT_SERVER }}
        OPENSHIFT_NAMESPACE=eb75ad
        ${{ secrets.GRAFANA_PROD_ENV }}
        EOF

    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: true

    - name: Deploy aggregator-promtail with Helm chart
      run: |
        make upgrade NAMESPACE=${{ env.OPENSHIFT_NAMESPACE }}-dev
        make upgrade NAMESPACE=${{ env.OPENSHIFT_NAMESPACE }}-test
        make upgrade NAMESPACE=${{ env.OPENSHIFT_NAMESPACE }}-prod
      working-directory: ./helm/promtail-aggregator

    - name: Deploy loki-promtail with Helm chart
      run: |
        make upgrade NAMESPACE=${{ env.OPENSHIFT_NAMESPACE }}-dev
        make upgrade NAMESPACE=${{ env.OPENSHIFT_NAMESPACE }}-test
        make upgrade NAMESPACE=${{ env.OPENSHIFT_NAMESPACE }}-prod
      working-directory: ./helm/promtail-loki
