name: Publish SSO Alloy Instance

on:
  push:
    branches:
    - main
    - dev
    paths:
    - helm/promtail-aggregator/**
    - helm/alloy/**
    - .github/workflows/deploy-alloy.yaml

jobs:
  helm-deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        source: mirror
        kam: latest
        oc: 4.18.7

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Set env to Sandbox
      if: (github.ref == 'refs/heads/dev' && github.event_name == 'push')
      run: |
        cat >> $GITHUB_ENV <<EOF
        OPENSHIFT_TOKEN=${{ secrets.SANDBOX_OPENSHIFT_TOKEN }}
        OPENSHIFT_SERVER=${{ secrets.SANDBOX_OPENSHIFT_SERVER }}
        OPENSHIFT_NAMESPACE=e4ca1d
        ${{ secrets.GRAFANA_SANDBOX_ENV }}
        EOF

    - name: Set env to Production
      if: (github.ref == 'refs/heads/main' && github.event_name == 'push')
      run: |
        cat >> $GITHUB_ENV <<EOF
        OPENSHIFT_TOKEN=${{ secrets.PROD_OPENSHIFT_TOKEN }}
        OPENSHIFT_SERVER=${{ secrets.PROD_OPENSHIFT_SERVER }}
        OPENSHIFT_NAMESPACE=eb75ad
        ${{ secrets.GRAFANA_PROD_ENV }}
        EOF

    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}

    - name: Deploy alloy with Helm chart
      run: |
        make deps
        make upgrade NAMESPACE=${{ env.OPENSHIFT_NAMESPACE }}-dev
        make upgrade NAMESPACE=${{ env.OPENSHIFT_NAMESPACE }}-test
        make upgrade NAMESPACE=${{ env.OPENSHIFT_NAMESPACE }}-prod
      working-directory: ./helm/alloy
