name: Check code/commit conventions

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Rerun Pre-Commit Hooks on CI
      run: pre-commit run --color=always --show-diff-on-failure --all-files

  commitlint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: wagoid/commitlint-github-action@v5
