name: Publish Loki

on:
  push:
    branches:
    - main
    - dev
    paths:
    - helm/loki/**
    - .github/workflows/publish-loki.yml

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - uses: hmarr/debug-action@v2
    - uses: actions/checkout@v3

    - name: Set env to Sandbox
      if: (github.ref == 'refs/heads/dev' && github.event_name == 'push')
      run: |
        cat >> $GITHUB_ENV <<EOF
        OPENSHIFT_TOKEN=${{ secrets.SANDBOX_OPENSHIFT_TOKEN }}
        OPENSHIFT_SERVER=${{ secrets.SANDBOX_OPENSHIFT_SERVER }}
        OPENSHIFT_NAMESPACE=${{ secrets.SANDBOX_OPENSHIFT_NAMESPACE }}
        S3_ACCESS_KEY_ID=${{ secrets.SANDBOX_S3_ACCESS_KEY_ID }}
        S3_SECRET_ACCESS_KEY=${{ secrets.SANDBOX_S3_SECRET_ACCESS_KEY }}
        EOF

    - name: Set env to Production
      if: (github.ref == 'refs/heads/main' && github.event_name == 'push')
      run: |
        cat >> $GITHUB_ENV <<EOF
        OPENSHIFT_TOKEN=${{ secrets.PROD_OPENSHIFT_TOKEN }}
        OPENSHIFT_SERVER=${{ secrets.PROD_OPENSHIFT_SERVER }}
        OPENSHIFT_NAMESPACE=${{ secrets.PROD_OPENSHIFT_NAMESPACE }}
        S3_ACCESS_KEY_ID=${{ secrets.PROD_S3_ACCESS_KEY_ID }}
        S3_SECRET_ACCESS_KEY=${{ secrets.PROD_S3_SECRET_ACCESS_KEY }}
        EOF

    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: true

    - name: Deploy loki with Helm chart
      run: |
        namespace=${{ env.OPENSHIFT_NAMESPACE }}
        helm dep up
        helm upgrade --install --atomic sso-loki . -n ${namespace} \
        -f values.yaml -f "values-${namespace}.yaml" \
        --set loki.storage.s3.access_key_id=${{ env.S3_ACCESS_KEY_ID }} \
        --set loki.storage.s3.secret_access_key=${{ env.S3_SECRET_ACCESS_KEY }}
      working-directory: ./helm/loki
