name: Terraform For Git Sync

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment to deploy to
        options:
        - sandbox
        - production
        default: sandbox
env:
  TF_VERSION: 1.15.5
  TERRAFORM_DEPLOY_ROLE_ARN: ''
  S3_BACKEND_NAME: ''
  GITHUB_REPO_URL: ''
  GITHUB_REPO_BRANCH: ''
  GITHUB_REPO_PATH: "'"
  GITHUB_REPO_SYNC_INTERVAL_SECONDS: ''
  GRAFANA_URL: ''
  GRAFANA_SERVICE_ACCOUNT_TOKEN: ''

jobs:
  terraform:
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure Common Variables
      run: |
        echo "GITHUB_REPO_URL=https://github.com/bcgov/sso-grafana-dashboards" >> $GITHUB_ENV
        echo "GITHUB_REPO_BRANCH=main" >> $GITHUB_ENV

    - name: Configure Sandbox Variables
      if: github.event.inputs.environment == 'sandbox'
      env:
        TERRAFORM_DEPLOY_ROLE_ARN_DEV: ${{ secrets.TERRAFORM_DEPLOY_ROLE_ARN_DEV }}
        SANDBOX_SSO_GRAFANA_SERVICE_ACCOUNT_TOKEN: ${{ secrets.SANDBOX_SSO_GRAFANA_SERVICE_ACCOUNT_TOKEN }}
      run: |
        echo "TERRAFORM_DEPLOY_ROLE_ARN=${{ env.TERRAFORM_DEPLOY_ROLE_ARN_DEV }}" >> $GITHUB_ENV
        echo "S3_BACKEND_NAME=grafana-git-sync-sandbox" >> $GITHUB_ENV
        echo "GITHUB_REPO_PATH=apps/sso/environments/sandbox" >> $GITHUB_ENV
        echo "GITHUB_REPO_SYNC_INTERVAL_SECONDS=3600" >> $GITHUB_ENV
        echo "GRAFANA_URL=https://sso-grafana-sandbox.apps.gold.devops.gov.bc.ca" >> $GITHUB_ENV
        echo "GRAFANA_SERVICE_ACCOUNT_TOKEN=${{ env.SANDBOX_SSO_GRAFANA_SERVICE_ACCOUNT_TOKEN }}" >> $GITHUB_ENV

    - name: Configure Production Variables
      if: github.event.inputs.environment == 'production'
      env:
        TERRAFORM_DEPLOY_ROLE_ARN_PROD: ${{ secrets.TERRAFORM_DEPLOY_ROLE_ARN_PROD }}
        PROD_SSO_GRAFANA_SERVICE_ACCOUNT_TOKEN: ${{ secrets.PROD_SSO_GRAFANA_SERVICE_ACCOUNT_TOKEN }}
      run: |
        echo "TERRAFORM_DEPLOY_ROLE_ARN=${{ env.TERRAFORM_DEPLOY_ROLE_ARN_PROD }}" >> $GITHUB_ENV
        echo "S3_BACKEND_NAME=grafana-git-sync-production" >> $GITHUB_ENV
        echo "GITHUB_REPO_PATH=apps/sso/environments/production" >> $GITHUB_ENV
        echo "GITHUB_REPO_SYNC_INTERVAL_SECONDS=3600" >> $GITHUB_ENV
        echo "GRAFANA_URL=https://sso-grafana.apps.gold.devops.gov.bc.ca" >> $GITHUB_ENV
        echo "GRAFANA_SERVICE_ACCOUNT_TOKEN=${{ env.PROD_SSO_GRAFANA_SERVICE_ACCOUNT_TOKEN }}" >> $GITHUB_ENV

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b
      with:
        role-to-assume: ${{ env.TERRAFORM_DEPLOY_ROLE_ARN }}
        aws-region: ca-central-1

    - name: Terraform Initialize
      working-directory: grafana/git-sync/terraform
      run: terraform init

    - name: Terraform Init
      working-directory: ./grafana/git-sync/terraform
      run: |
        cat <<EOF > backend.hcl
        bucket = "${{ env.S3_BACKEND_NAME }}"
        key = "tf-state"
        region = "ca-central-1"
        EOF
        terraform init -backend-config=backend.hcl

    - name: Terraform Variables
      env:
        GIT_SYNC_GITHUB_APP_ID: ${{ secrets.GIT_SYNC_GITHUB_APP_ID }}
        GIT_SYNC_GITHUB_APP_INSTALLATION_ID: ${{ secrets.GIT_SYNC_GITHUB_APP_INSTALLATION_ID }}
        GIT_SYNC_GITHUB_APP_PRIVATE_KEY_B64_ENCODED: ${{ secrets.GIT_SYNC_GITHUB_APP_PRIVATE_KEY_B64_ENCODED }}
      working-directory: ./grafana/git-sync/terraform
      run: |
        cat >"ci.auto.tfvars" <<EOF
          github_app_id = "${{ env.GIT_SYNC_GITHUB_APP_ID }}"
          github_app_installation_id = "${{ env.GIT_SYNC_GITHUB_APP_INSTALLATION_ID }}"
          github_app_private_key_b64_encoded = "${{ env.GIT_SYNC_GITHUB_APP_PRIVATE_KEY_B64_ENCODED }}"
          repo_url = "${{ env.GITHUB_REPO_URL }}"
          repo_branch = "${{ env.GITHUB_REPO_BRANCH }}"
          repo_path = "${{ env.GITHUB_REPO_PATH }}"
          repo_sync_interval_seconds = "${{ env.GITHUB_REPO_SYNC_INTERVAL_SECONDS }}"
          grafana_url = "${{ env.GRAFANA_URL }}"
          grafana_service_account_token = "${{ env.GRAFANA_SERVICE_ACCOUNT_TOKEN }}"
        EOF

    - name: Terraform Plan
      run: terraform plan -no-color
      working-directory: ./grafana/git-sync/terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./grafana/git-sync/terraform
