name: Go CI

on:
  push:
    branches: [ssoteam-1456]

defaults:
  run:
    working-directory: aggregator

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.21.0

    - name: Install dependencies
      run: go mod download

    - name: Run kc tests
      run: |
        cd keycloak
        go test

    - name: Run session tests
      run: |
        cd ../model
        go test
